name = "Mathling"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Mathling"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[require]]
name = "literate-lean"
git = "https://github.com/tani/literate-lean.git"
rev = "main"

[[require]]
name = "cslib"
scope = "leanprover"
rev = "v4.28.0"

[[lean_lib]]
name = "Mathling"
