name = "Mathling"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Mathling"]
testDriver = "mathlingTests"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.emptyLine = false
weak.linter.style.whitespace = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[require]]
name = "literate-lean"
git = "https://github.com/tani/literate-lean.git"
rev = "main"

[[require]]
name = "cslib"
scope = "leanprover"
rev = "v4.32.0"

[[lean_lib]]
name = "Mathling"

[[lean_exe]]
name = "mathlingTests"
root = "Tests.Main"
