import Mathlib.Data.List.Basic
import Mathlib.Data.Nat.Basic

/-!
# CCG categories and the finite candidate set

This module formalizes the syntax layer of the eight-rule CCG system described
in `ccg_blueprint.tex` and `ccg_decidability_proof_3-1.pdf`.

Categories are generated by atoms, right division `/` and left division `\`.
Alongside the datatype we record the structural measures used by the blueprint
(`depth`, `constructors`, `atoms`), their context-level versions, the schematic
bounds `V` and `H`, and a mechanical generator for the finite candidate
category set `K_{Γ,y}`.
-/

namespace Mathling.CCG

set_option linter.style.setOption false

/-- CCG categories: atoms, left division, and right division. -/
@[grind cases]
inductive Tp where
  | atom (name : String) : Tp
  | ldiv (A B : Tp) : Tp
  | rdiv (A B : Tp) : Tp
  deriving Repr, DecidableEq

namespace Tp

prefix:65 "#" => Tp.atom
infixr:60 " ⧹ " => Tp.ldiv
infixl:60 " ⧸ " => Tp.rdiv

/-- The depth `d(A)` from the proof: atoms have depth `0`. -/
@[grind =]
def depth : Tp → Nat
  | # _ => 0
  | A ⧹ B => Nat.max (depth A) (depth B) + 1
  | A ⧸ B => Nat.max (depth A) (depth B) + 1

/-- The number `c(A)` of slash constructors in a category. -/
@[grind =]
def constructors : Tp → Nat
  | # _ => 0
  | A ⧹ B => constructors A + constructors B + 1
  | A ⧸ B => constructors A + constructors B + 1

/-- The atoms occurring in a category, with possible duplicates. -/
@[grind =]
def atoms : Tp → List String
  | # name => [name]
  | A ⧹ B => atoms A ++ atoms B
  | A ⧸ B => atoms A ++ atoms B

/-- Homomorphic action of a map on atoms. -/
@[grind =]
def mapAtoms (f : String → String) : Tp → Tp
  | # name => # (f name)
  | A ⧹ B => mapAtoms f A ⧹ mapAtoms f B
  | A ⧸ B => mapAtoms f A ⧸ mapAtoms f B

@[simp, grind =]
theorem mapAtoms_atom (f : String → String) (name : String) :
    mapAtoms f (# name) = # (f name) := rfl

@[simp, grind =]
theorem mapAtoms_ldiv (f : String → String) (A B : Tp) :
    mapAtoms f (A ⧹ B) = mapAtoms f A ⧹ mapAtoms f B := rfl

@[simp, grind =]
theorem mapAtoms_rdiv (f : String → String) (A B : Tp) :
    mapAtoms f (A ⧸ B) = mapAtoms f A ⧸ mapAtoms f B := rfl

end Tp

open Tp

/-- Constructor count of a context. -/
@[grind =]
def contextConstructors : List Tp → Nat
  | [] => 0
  | A :: Γ => A.constructors + contextConstructors Γ

/-- Maximum category depth in a context. -/
@[grind =]
def contextDepth : List Tp → Nat
  | [] => 0
  | A :: Γ => Nat.max A.depth (contextDepth Γ)

/-- Atoms occurring in a context, with possible duplicates. -/
@[grind =]
def contextAtoms : List Tp → List String
  | [] => []
  | A :: Γ => A.atoms ++ contextAtoms Γ

/-- Constructor counts are additive over context append. -/
@[grind =]
theorem contextConstructors_append (Γ Δ : List Tp) :
    contextConstructors (Γ ++ Δ) = contextConstructors Γ + contextConstructors Δ := by
  induction Γ <;> grind

/-- Atoms occurring in the input and target of a recognition problem. -/
@[grind =]
def problemAtoms (Γ : List Tp) (goal : Tp) : List String :=
  (contextAtoms Γ ++ goal.atoms).eraseDups

/-- The visible-occurrence bound `V` used in the paper. -/
@[grind =]
def visibleBound (Γ : List Tp) (goal : Tp) : Nat :=
  contextConstructors Γ + goal.constructors + 3 * (Γ.length - 1)

/-- The schematic depth bound `H = V + q*r*V*(V+1)` from the paper. -/
@[grind =]
def depthBound (q r : Nat) (Γ : List Tp) (goal : Tp) : Nat :=
  let V := visibleBound Γ goal
  V + q * r * V * (V + 1)

/-- One step of the category generator over an already finite list. -/
@[grind =]
def closeOnce (xs : List Tp) : List Tp :=
  (xs ++ xs.flatMap (fun A => xs.flatMap (fun B => [A ⧹ B, A ⧸ B]))).eraseDups

/-- All categories over `atoms` of depth at most the given bound.

This is intentionally simple and finite.  It is the finite set
`K_{Γ,y}` of the blueprint when `atoms = Σ` and `depthLimit = H(Γ,y)`. -/
@[grind =]
def categoriesUpTo : Nat → List String → List Tp
  | 0, atoms => (atoms.eraseDups.map (fun name => # name)).eraseDups
  | n + 1, atoms => closeOnce (categoriesUpTo n atoms)

/-- The finite candidate category set for an input/goal pair and a depth limit. -/
@[grind =]
def candidateCategories (Γ : List Tp) (goal : Tp) (depthLimit : Nat) : List Tp :=
  categoriesUpTo depthLimit (problemAtoms Γ goal)

end Mathling.CCG
