module

public import Mathlib.Data.List.Basic
public import Mathlib.Data.Nat.Basic

@[expose] public section

/-!
# CCG categories and the finite candidate set

This module formalizes the syntax layer of the eight-rule CCG system described
in `ccg_blueprint.tex` and `ccg_decidability_proof_3-1.pdf`.

Categories are generated by atoms, right division `/` and left division `\`.
Alongside the datatype we record the structural measures used by the blueprint
(`depth`, `constructors`, `atoms`), their context-level versions, the schematic
bounds `V` and `H`, and a mechanical generator for the finite candidate
category set `K_{Γ,y}`.
-/

namespace Mathling.CCG

set_option linter.style.setOption false

/-- CCG categories: atoms, left division, and right division. -/
@[grind cases]
inductive Category where
  | atom (name : String) : Category
  | ldiv (A B : Category) : Category
  | rdiv (A B : Category) : Category
  deriving Repr, DecidableEq

namespace Category

prefix:65 "#" => Category.atom
infixr:60 " ⧹ " => Category.ldiv
infixl:60 " ⧸ " => Category.rdiv

/-- The depth `d(A)` from the proof: atoms have depth `0`. -/
@[grind =]
def depth : Category → Nat
  | # _ => 0
  | A ⧹ B => Nat.max (depth A) (depth B) + 1
  | A ⧸ B => Nat.max (depth A) (depth B) + 1

/-- The number `c(A)` of slash constructors in a category. -/
@[grind =]
def constructors : Category → Nat
  | # _ => 0
  | A ⧹ B => constructors A + constructors B + 1
  | A ⧸ B => constructors A + constructors B + 1

/-- The atoms occurring in a category, with possible duplicates. -/
@[grind =]
def atoms : Category → List String
  | # name => [name]
  | A ⧹ B => atoms A ++ atoms B
  | A ⧸ B => atoms A ++ atoms B

/-- Homomorphic action of a map on atoms. -/
@[grind =]
def mapAtoms (f : String → String) : Category → Category
  | # name => # (f name)
  | A ⧹ B => mapAtoms f A ⧹ mapAtoms f B
  | A ⧸ B => mapAtoms f A ⧸ mapAtoms f B

@[simp, grind =]
theorem mapAtoms_atom (f : String → String) (name : String) :
    mapAtoms f (# name) = # (f name) := rfl

@[simp, grind =]
theorem mapAtoms_ldiv (f : String → String) (A B : Category) :
    mapAtoms f (A ⧹ B) = mapAtoms f A ⧹ mapAtoms f B := rfl

@[simp, grind =]
theorem mapAtoms_rdiv (f : String → String) (A B : Category) :
    mapAtoms f (A ⧸ B) = mapAtoms f A ⧸ mapAtoms f B := rfl

end Category

open Category

/-- Constructor count of a context. -/
@[grind =]
def contextConstructors : List Category → Nat
  | [] => 0
  | A :: Γ => A.constructors + contextConstructors Γ

/-- Maximum category depth in a context. -/
@[grind =]
def contextDepth : List Category → Nat
  | [] => 0
  | A :: Γ => Nat.max A.depth (contextDepth Γ)

/-- Atoms occurring in a context, with possible duplicates. -/
@[grind =]
def contextAtoms : List Category → List String
  | [] => []
  | A :: Γ => A.atoms ++ contextAtoms Γ

/-- Constructor counts are additive over context append. -/
@[grind =]
theorem contextConstructors_append (Γ Δ : List Category) :
    contextConstructors (Γ ++ Δ) = contextConstructors Γ + contextConstructors Δ := by
  induction Γ <;> grind

/-- Atoms occurring in the input and target of a recognition problem. -/
@[grind =]
def problemAtomNames (Γ : List Category) (goal : Category) : List String :=
  (contextAtoms Γ ++ goal.atoms).eraseDups

/-- The visible-occurrence bound `V` used in the paper. -/
@[grind =]
def visibleBound (Γ : List Category) (goal : Category) : Nat :=
  contextConstructors Γ + goal.constructors + 3 * (Γ.length - 1)

/-- The depth bound `H = V + V*r`.

A root-to-leaf constructor branch of an intermediate category carries at most
`V` visible occurrences.  Every invisible occurrence lies in an invisible trace
piece; trace edges preserve the addressed subcategory, so a piece meets one
branch at most once, and a piece with a visible boundary is determined by a
pair (visible occurrence, trace-neighbour slot) — at most `V*r` choices.
Hence every branch has length at most `V + V*r`.

This sharpens the draft paper's `H = V + q*r*V*(V+1)`: the interface-state
factor `q` and the zone factor `V+1` are unnecessary, because two distinct
occurrences on one branch can never lie in the same trace piece at all. -/
@[grind =]
def depthBound (r : Nat) (Γ : List Category) (goal : Category) : Nat :=
  let V := visibleBound Γ goal
  V + V * r

/-- One step of the category generator over an already finite list. -/
@[grind =]
def addOneLayer (xs : List Category) : List Category :=
  (xs ++ xs.flatMap (fun A => xs.flatMap (fun B => [A ⧹ B, A ⧸ B]))).eraseDups

/-- All categories over `atoms` of depth at most the given bound.

This is intentionally simple and finite.  It is the finite set
`K_{Γ,y}` of the blueprint when `atoms = Σ` and `depthLimit = H(Γ,y)`. -/
@[grind =]
def categoriesWithDepthAtMost : Nat → List String → List Category
  | 0, atoms => (atoms.eraseDups.map (fun name => # name)).eraseDups
  | n + 1, atoms => addOneLayer (categoriesWithDepthAtMost n atoms)

/-- The finite candidate category set for an input/goal pair and a depth limit. -/
@[grind =]
def categoryPool (Γ : List Category) (goal : Category) (depthLimit : Nat) : List Category :=
  categoriesWithDepthAtMost depthLimit (problemAtomNames Γ goal)

namespace Category

/-- Category depth is bounded by the number of slash constructors. -/
@[grind =>]
theorem depth_le_constructors : ∀ A : Category, A.depth ≤ A.constructors
  | # _ => by simp [depth, constructors]
  | A ⧹ B => by
      have hA := depth_le_constructors A
      have hB := depth_le_constructors B
      simp only [depth, constructors]
      exact Nat.succ_le_succ
        (Nat.max_le.mpr ⟨
          (le_trans hA (Nat.le_add_right A.constructors B.constructors)),
          (le_trans hB (Nat.le_add_left B.constructors A.constructors))⟩)
  | A ⧸ B => by
      have hA := depth_le_constructors A
      have hB := depth_le_constructors B
      simp only [depth, constructors]
      exact Nat.succ_le_succ
        (Nat.max_le.mpr ⟨
          (le_trans hA (Nat.le_add_right A.constructors B.constructors)),
          (le_trans hB (Nat.le_add_left B.constructors A.constructors))⟩)

end Category

end Mathling.CCG
