module

public import Mathling.CCG.Category

@[expose] public section

/-!
# The finite candidate category set `K_{Γ,y}` (paper §23)

This module proves the *finite candidate set* part of
`ccg_decidability_proof_3-1.pdf`, §23: the mechanically generated list
`categoriesWithDepthAtMost n atoms` contains **every** category whose atoms lie in `atoms`
and whose depth is at most `n`.  Combined with the paper's depth bound
`H(Γ,y)`, this is exactly the statement that `categoryPool` is a complete
finite chart alphabet for any bounded-normal-form derivation.

These are genuine, axiom-free Lean proofs.  The headline result is
`mem_categoriesWithDepthAtMost_of_atoms_depth` and its specialization
`mem_categoryPool_of_atoms_depth`.
-/

namespace Mathling.CCG

open Category List

/-! ## `eraseDups` membership

`List.eraseDups` in this toolchain (Lean v4.28.0) exposes only the `nil`/`cons`
equations, not a membership lemma, so we prove the membership characterization
by induction on length. -/

/-- Auxiliary length-bounded induction for `eraseDups` membership. -/
private theorem mem_eraseDups_iff_aux {α} [BEq α] [LawfulBEq α] {a : α} :
    ∀ (n : Nat) (l : List α), l.length ≤ n → (a ∈ l.eraseDups ↔ a ∈ l) := by
  intro n
  induction n with
  | zero =>
      intro l hl
      have : l = [] := by
        cases l with
        | nil => rfl
        | cons x xs => simp at hl
      subst this; simp
  | succ n ih =>
      intro l hl
      cases l with
      | nil => simp
      | cons x xs =>
          rw [List.eraseDups_cons]
          simp only [List.mem_cons]
          have hlen : (xs.filter (fun b => !b == x)).length ≤ n := by
            have h1 := List.length_filter_le (fun b => !b == x) xs
            have h2 : xs.length ≤ n := by simpa [Nat.succ_le_succ_iff] using hl
            omega
          rw [ih _ hlen]
          constructor
          · rintro (rfl | h)
            · exact Or.inl rfl
            · exact Or.inr (List.mem_of_mem_filter h)
          · rintro (rfl | h)
            · exact Or.inl rfl
            · by_cases hax : a == x
              · exact Or.inl (by simpa using hax)
              · exact Or.inr (List.mem_filter.mpr ⟨h, by simp [hax]⟩)

/-- Membership is preserved by `eraseDups`. -/
@[grind =]
theorem mem_eraseDups_iff {α} [BEq α] [LawfulBEq α] {a : α} {l : List α} :
    a ∈ l.eraseDups ↔ a ∈ l :=
  mem_eraseDups_iff_aux l.length l le_rfl

/-! ## One generator step -/

/-- Membership characterization of one `addOneLayer` step. -/
@[grind =]
theorem mem_closeOnce {xs : List Category} {C : Category} :
    C ∈ addOneLayer xs ↔
      C ∈ xs ∨ ∃ A ∈ xs, ∃ B ∈ xs, C = A ⧹ B ∨ C = A ⧸ B := by
  unfold addOneLayer
  rw [mem_eraseDups_iff, List.mem_append]
  constructor
  · rintro (h | h)
    · exact Or.inl h
    · rw [List.mem_flatMap] at h
      obtain ⟨A, hA, hh⟩ := h
      rw [List.mem_flatMap] at hh
      obtain ⟨B, hB, hh⟩ := hh
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hh
      exact Or.inr ⟨A, hA, B, hB, hh⟩
  · rintro (h | ⟨A, hA, B, hB, hh⟩)
    · exact Or.inl h
    · right
      rw [List.mem_flatMap]
      refine ⟨A, hA, ?_⟩
      rw [List.mem_flatMap]
      refine ⟨B, hB, ?_⟩
      simp only [List.mem_cons, List.not_mem_nil, or_false]
      exact hh

/-! ## Monotonicity in the depth bound -/

/-- Raising the bound by one only adds categories. -/
theorem categoriesWithDepthAtMost_subset_succ (n : Nat) (atoms : List String) :
    categoriesWithDepthAtMost n atoms ⊆ categoriesWithDepthAtMost (n + 1) atoms := by
  intro C hC
  show C ∈ categoriesWithDepthAtMost (n + 1) atoms
  rw [categoriesWithDepthAtMost, mem_closeOnce]
  exact Or.inl hC

/-- `categoriesWithDepthAtMost` is monotone in the depth bound. -/
theorem categoriesWithDepthAtMost_mono {m n : Nat} (h : m ≤ n) (atoms : List String) :
    categoriesWithDepthAtMost m atoms ⊆ categoriesWithDepthAtMost n atoms := by
  induction h with
  | refl => exact fun _ hx => hx
  | step _ ih => exact fun C hC => categoriesWithDepthAtMost_subset_succ _ _ (ih hC)

/-- Atoms occur at every level of the generator. -/
theorem atom_mem_categoriesWithDepthAtMost {name : String} {atoms : List String}
    (h : name ∈ atoms) (n : Nat) : (# name) ∈ categoriesWithDepthAtMost n atoms := by
  have base : (# name) ∈ categoriesWithDepthAtMost 0 atoms := by
    rw [categoriesWithDepthAtMost, mem_eraseDups_iff, List.mem_map]
    exact ⟨name, by rw [mem_eraseDups_iff]; exact h, rfl⟩
  exact categoriesWithDepthAtMost_mono (Nat.zero_le n) atoms base

/-! ## §23 completeness of the finite candidate set -/

/-- **Paper §23.**  Every category whose atoms lie in `atoms` and whose depth is
at most `n` is generated by `categoriesWithDepthAtMost n atoms`. -/
theorem mem_categoriesWithDepthAtMost_of_atoms_depth :
    ∀ (C : Category) (atoms : List String) (n : Nat),
      (∀ name ∈ C.atoms, name ∈ atoms) → C.depth ≤ n →
      C ∈ categoriesWithDepthAtMost n atoms := by
  intro C
  induction C with
  | atom name =>
      intro atoms n hat _
      have hname : name ∈ (# name : Category).atoms := by
        change name ∈ [name]; exact List.mem_singleton.mpr rfl
      exact atom_mem_categoriesWithDepthAtMost (hat name hname) n
  | ldiv A B ihA ihB =>
      intro atoms n hat hdep
      cases n with
      | zero =>
          have hdeq : (A ⧹ B).depth = Nat.max A.depth B.depth + 1 := rfl
          rw [hdeq] at hdep; omega
      | succ m =>
          have hdeq : (A ⧹ B).depth = Nat.max A.depth B.depth + 1 := rfl
          rw [hdeq] at hdep
          have hmax : Nat.max A.depth B.depth ≤ m := by omega
          have hA : A.depth ≤ m := le_trans (Nat.le_max_left _ _) hmax
          have hB : B.depth ≤ m := le_trans (Nat.le_max_right _ _) hmax
          have hatA : ∀ name ∈ A.atoms, name ∈ atoms := fun nm hnm =>
            hat nm (by
              have : (A ⧹ B).atoms = A.atoms ++ B.atoms := rfl
              rw [this]; exact List.mem_append.mpr (Or.inl hnm))
          have hatB : ∀ name ∈ B.atoms, name ∈ atoms := fun nm hnm =>
            hat nm (by
              have : (A ⧹ B).atoms = A.atoms ++ B.atoms := rfl
              rw [this]; exact List.mem_append.mpr (Or.inr hnm))
          have hmA := ihA atoms m hatA hA
          have hmB := ihB atoms m hatB hB
          change (A ⧹ B) ∈ categoriesWithDepthAtMost (m + 1) atoms
          rw [categoriesWithDepthAtMost, mem_closeOnce]
          exact Or.inr ⟨A, hmA, B, hmB, Or.inl rfl⟩
  | rdiv A B ihA ihB =>
      intro atoms n hat hdep
      cases n with
      | zero =>
          have hdeq : (A ⧸ B).depth = Nat.max A.depth B.depth + 1 := rfl
          rw [hdeq] at hdep; omega
      | succ m =>
          have hdeq : (A ⧸ B).depth = Nat.max A.depth B.depth + 1 := rfl
          rw [hdeq] at hdep
          have hmax : Nat.max A.depth B.depth ≤ m := by omega
          have hA : A.depth ≤ m := le_trans (Nat.le_max_left _ _) hmax
          have hB : B.depth ≤ m := le_trans (Nat.le_max_right _ _) hmax
          have hatA : ∀ name ∈ A.atoms, name ∈ atoms := fun nm hnm =>
            hat nm (by
              have : (A ⧸ B).atoms = A.atoms ++ B.atoms := rfl
              rw [this]; exact List.mem_append.mpr (Or.inl hnm))
          have hatB : ∀ name ∈ B.atoms, name ∈ atoms := fun nm hnm =>
            hat nm (by
              have : (A ⧸ B).atoms = A.atoms ++ B.atoms := rfl
              rw [this]; exact List.mem_append.mpr (Or.inr hnm))
          have hmA := ihA atoms m hatA hA
          have hmB := ihB atoms m hatB hB
          change (A ⧸ B) ∈ categoriesWithDepthAtMost (m + 1) atoms
          rw [categoriesWithDepthAtMost, mem_closeOnce]
          exact Or.inr ⟨A, hmA, B, hmB, Or.inr rfl⟩

/-- Specialization to `categoryPool`: any category drawn from the problem
atoms with depth at most `depthLimit` is a candidate. -/
theorem mem_categoryPool_of_atoms_depth
    {Γ : List Category} {goal : Category} {depthLimit : Nat} {C : Category}
    (hat : ∀ name ∈ C.atoms, name ∈ problemAtomNames Γ goal)
    (hdep : C.depth ≤ depthLimit) :
    C ∈ categoryPool Γ goal depthLimit :=
  mem_categoriesWithDepthAtMost_of_atoms_depth C (problemAtomNames Γ goal) depthLimit hat hdep

end Mathling.CCG
