module

public import Mathling.Grammar.Regular.RightLinear

@[expose] public section

/-!
# Left-linear grammars

Left-linear grammars, reversal to right-linear grammars, and regularity.
-/

namespace Mathling.Grammar

namespace LeftLinearGrammar

variable {T : Type*}

/-- The language generated by a left-linear grammar. -/
def language (g : LeftLinearGrammar T) : Language T := g.cfg.language

/-- Forget that a left-linear grammar is left-linear. -/
def toLinear (g : LeftLinearGrammar T) : LinearGrammar T where
  cfg := g.cfg
  linear r hr := by
    rcases g.leftLinear r hr with h | ⟨a, h⟩ | ⟨A, a, h⟩ <;>
      simp [ContextFreeRule.IsLinear, ContextFreeRule.nonterminalCount,
        symbolIsNonterminal, h]

end LeftLinearGrammar

namespace LeftLinearGrammar

variable {T : Type*}

/-- Reverse every production of a left-linear grammar to obtain a right-linear grammar. -/
def reverseRightLinear (g : LeftLinearGrammar T) : RightLinearGrammar T where
  cfg := g.cfg.reverse
  rightLinear r hr := by
    change ContextFreeRule T g.cfg.NT at r
    change r ∈ g.cfg.rules.map
      ⟨ContextFreeRule.reverse, ContextFreeRule.reverse_injective⟩ at hr
    obtain ⟨source, hsource, rfl⟩ := Finset.mem_map.mp hr
    rcases g.leftLinear source hsource with h | ⟨a, h⟩ | ⟨A, a, h⟩
    · exact Or.inl (by simp [ContextFreeRule.reverse, h]; rfl)
    · exact Or.inr (Or.inl ⟨a, by
        simp [ContextFreeRule.reverse, h]
        rfl⟩)
    · exact Or.inr (Or.inr ⟨a, A, by
        simp [ContextFreeRule.reverse, h]
        rfl⟩)

/-- Reversing productions reverses the generated language. -/
@[simp] theorem reverseRightLinear_language (g : LeftLinearGrammar T) :
    g.reverseRightLinear.language = g.language.reverse := by
  simp [reverseRightLinear, RightLinearGrammar.language, LeftLinearGrammar.language]

/-- A left-linear grammar with finitely many nonterminals generates a regular language. -/
theorem language_isRegular (g : LeftLinearGrammar T) [Fintype g.cfg.NT] :
    g.language.IsRegular := by
  letI : Fintype g.reverseRightLinear.cfg.NT := by
    change Fintype g.cfg.NT
    infer_instance
  apply Language.isRegular_reverse_iff.mp
  rw [← g.reverseRightLinear_language]
  exact g.reverseRightLinear.language_isRegular

end LeftLinearGrammar

end Mathling.Grammar
