    module

    public import Mathling.Grammar.Regular.Right
    public import Mathling.Meta.Important

    import LiterateLean
    open scoped LiterateLean


# Mathling / Grammar / Regular / Left モジュール

左線形文法を規則右辺の反転によって右線形文法へ移し、生成言語が語の反転で対応することを証明する。この橋渡しにより、有限非終端記号を持つ左線形文法の正則性を右線形文法の結果から再利用する。

```lean

/-!
# Left-linear grammars

Left-linear grammars, reversal to right-linear grammars, and regularity.
-/



namespace Mathling.Grammar

```

```lean
namespace LeftLinearGrammar

```

```lean
variable {T : Type*}

/-- The language generated by a left-linear grammar.

Its body is exposed because public reversal results identify it with the
reversed language of the associated right-linear grammar. -/


@[expose] public def language (g : LeftLinearGrammar T) : Language T := g.cfg.language
```

```lean
/-- Every left-linear grammar is context-free after forgetting its rule-shape
certificate. -/


@[important, grind .] public theorem language_isContextFree (g : LeftLinearGrammar T) :
    g.language.IsContextFree :=
  ⟨g.cfg, rfl⟩
```

```lean
/-- Forget that a left-linear grammar is left-linear. -/
public def toLinear (g : LeftLinearGrammar T) : LinearGrammar T where
  cfg := g.cfg
  linear r hr := by
    rcases g.leftLinear r hr with h | ⟨a, h⟩ | ⟨A, a, h⟩ <;>
      simp [ContextFreeRule.IsLinear, ContextFreeRule.nonterminalCount,
        symbolIsNonterminal, h]
```

```lean
@[important, grind =, simp] public theorem toLinear_language (g : LeftLinearGrammar T) :
    g.toLinear.language = g.language := rfl

end LeftLinearGrammar

```

## 規則反転の局所形状

空右辺と終端一個の右辺は反転で変わらず、二記号の右辺だけが順序を交換する。
この三ケースが左右線形規則の形状述語を相互に変換する局所的な根拠になる。

```lean
/-- Reversing a rule with empty output leaves the output empty. -/
@[grind .] private theorem ContextFreeRule.reverse_output_nil {T N : Type*}
    {r : ContextFreeRule T N} (h : r.output = []) : r.reverse.output = [] := by
  simp [ContextFreeRule.reverse, h]
```

```lean
/-- Reversing a rule with singleton output leaves the output unchanged. -/
@[grind .] private theorem ContextFreeRule.reverse_output_singleton {T N : Type*}
    {r : ContextFreeRule T N} {a : T} (h : r.output = [Symbol.terminal a]) :
    r.reverse.output = [Symbol.terminal a] := by
  simp [ContextFreeRule.reverse, h]
```

```lean
/-- Reversing a rule with two-symbol output swaps the two symbols. -/
@[grind .] private theorem ContextFreeRule.reverse_output_pair {T N : Type*}
    {r : ContextFreeRule T N} {x y : Symbol T N} (h : r.output = [x, y]) :
    r.reverse.output = [y, x] := by
  simp [ContextFreeRule.reverse, h]
```

## 左線形文法から右線形文法へ

各規則を反転して右線形文法を構成する。文法の反転定理により生成語も反転するため、
有限非終端記号の場合の正則性は既存の右線形結果から移送できる。

```lean
namespace LeftLinearGrammar

```

```lean
variable {T : Type*}

/-- Reverse every production of a left-linear grammar to obtain a right-linear grammar. -/
public def reverseRightLinear (g : LeftLinearGrammar T) : RightLinearGrammar T where
  cfg := g.cfg.reverse
  rightLinear r hr := by
    change ContextFreeRule T g.cfg.NT at r
    change r ∈ g.cfg.rules.map
      ⟨ContextFreeRule.reverse, ContextFreeRule.reverse_injective⟩ at hr
    obtain ⟨source, hsource, rfl⟩ := Finset.mem_map.mp hr
    rcases g.leftLinear source hsource with h | ⟨a, h⟩ | ⟨A, a, h⟩
    · exact Or.inl (ContextFreeRule.reverse_output_nil h)
    · exact Or.inr (Or.inl ⟨a, ContextFreeRule.reverse_output_singleton h⟩)
    · exact Or.inr (Or.inr ⟨a, A, ContextFreeRule.reverse_output_pair h⟩)
```

```lean
/-- Reversing productions reverses the generated language. -/
@[grind =, simp] theorem reverseRightLinear_language (g : LeftLinearGrammar T) :
    g.reverseRightLinear.language = g.language.reverse := by
  simp [reverseRightLinear, RightLinearGrammar.language, LeftLinearGrammar.language]
```

```lean
/-- A left-linear grammar with finitely many nonterminals generates a regular language. -/
@[grind .] theorem language_isRegular (g : LeftLinearGrammar T) [Finite g.cfg.NT] :
    g.language.IsRegular := by
  letI := Fintype.ofFinite g.cfg.NT
  letI : Fintype g.reverseRightLinear.cfg.NT := by
    change Fintype g.cfg.NT
    infer_instance
  apply Language.isRegular_reverse_iff.mp
  rw [← g.reverseRightLinear_language]
  exact g.reverseRightLinear.language_isRegular

end LeftLinearGrammar
```

## 右線形文法から左線形文法へ

逆方向にも同じ規則反転を使う。反転は involution なので、右線形文法の言語を反転した
言語を生成する左線形文法が得られ、最終的な存在同値の witness を構成できる。

```lean
namespace RightLinearGrammar

```

```lean
variable {T : Type*}

/-- Reverse every production of a right-linear grammar to obtain a left-linear grammar. -/
public def reverseLeftLinear (g : RightLinearGrammar T) : LeftLinearGrammar T where
  cfg := g.cfg.reverse
  leftLinear r hr := by
    change ContextFreeRule T g.cfg.NT at r
    change r ∈ g.cfg.rules.map
      ⟨ContextFreeRule.reverse, ContextFreeRule.reverse_injective⟩ at hr
    obtain ⟨source, hsource, rfl⟩ := Finset.mem_map.mp hr
    rcases g.rightLinear source hsource with h | ⟨a, h⟩ | ⟨a, B, h⟩
    · exact Or.inl (ContextFreeRule.reverse_output_nil h)
    · exact Or.inr (Or.inl ⟨a, ContextFreeRule.reverse_output_singleton h⟩)
    · exact Or.inr (Or.inr ⟨B, a, ContextFreeRule.reverse_output_pair h⟩)
```

```lean
/-- Reversing productions reverses the generated language. -/
@[grind =, simp] theorem reverseLeftLinear_language (g : RightLinearGrammar T) :
    g.reverseLeftLinear.language = g.language.reverse := by
  simp [reverseLeftLinear, LeftLinearGrammar.language, RightLinearGrammar.language]

end RightLinearGrammar
```

## 正則性の左線形文法による特徴付け

語の反転が正則性を保つことと、右線形文法による既存の特徴付けを合成する。
有限アルファベットと有限非終端記号は、逆向き witness の有限オートマトン性を保証する。

```lean
/-- Over finite alphabets, regular languages are exactly the left-linear languages
with a finite nonterminal type: reverse a right-linear witness for the reversed
language back into a left-linear witness for the original language. -/


@[important, grind =] public theorem Language.isRegular_iff_exists_leftLinearGrammar
    {T : Type} [Finite T] {L : Language T} :
    L.IsRegular ↔
      ∃ g : LeftLinearGrammar T, Nonempty (Fintype g.cfg.NT) ∧ g.language = L := by
  letI := Fintype.ofFinite T
  constructor
  · intro hL
    have hrev : L.reverse.IsRegular := Language.isRegular_reverse_iff.mpr hL
    obtain ⟨g, ⟨inst⟩, hg⟩ := Language.isRegular_iff_exists_rightLinearGrammar.mp hrev
    refine ⟨g.reverseLeftLinear, ⟨inst⟩, ?_⟩
    rw [g.reverseLeftLinear_language, hg, Language.reverse_reverse]
  · rintro ⟨g, ⟨inst⟩, rfl⟩
    letI : Fintype g.cfg.NT := inst
    exact g.language_isRegular

end Mathling.Grammar

```

<!--
vim: set filetype=markdown :
Local Variables:
mode: markdown
End:
-->
