    module

    public import Mathling.Grammar.Regular.RightLinear

    public import LiterateLean
    open scoped LiterateLean

    @[expose] public section

# Mathling / Grammar / Regular / LeftLinear モジュール

このモジュールは Mathling のこの領域に属する定義、変換、および証明を提供する。公開される契約と依存関係は import 境界で明示し、実装は以下の Lean ブロックに限定する。

```lean
@[expose] public section

/-!
# Left-linear grammars

Left-linear grammars, reversal to right-linear grammars, and regularity.
-/

namespace Mathling.Grammar

namespace LeftLinearGrammar

variable {T : Type*}

/-- The language generated by a left-linear grammar. -/
def language (g : LeftLinearGrammar T) : Language T := g.cfg.language

/-- Forget that a left-linear grammar is left-linear. -/
def toLinear (g : LeftLinearGrammar T) : LinearGrammar T where
  cfg := g.cfg
  linear r hr := by
    rcases g.leftLinear r hr with h | ⟨a, h⟩ | ⟨A, a, h⟩ <;>
      simp [ContextFreeRule.IsLinear, ContextFreeRule.nonterminalCount,
        symbolIsNonterminal, h]

end LeftLinearGrammar

/-- Reversing a rule with empty output leaves the output empty. -/
private theorem ContextFreeRule.reverse_output_nil {T N : Type*}
    {r : ContextFreeRule T N} (h : r.output = []) : r.reverse.output = [] := by
  simp [ContextFreeRule.reverse, h]

/-- Reversing a rule with singleton output leaves the output unchanged. -/
private theorem ContextFreeRule.reverse_output_singleton {T N : Type*}
    {r : ContextFreeRule T N} {a : T} (h : r.output = [Symbol.terminal a]) :
    r.reverse.output = [Symbol.terminal a] := by
  simp [ContextFreeRule.reverse, h]

/-- Reversing a rule with two-symbol output swaps the two symbols. -/
private theorem ContextFreeRule.reverse_output_pair {T N : Type*}
    {r : ContextFreeRule T N} {x y : Symbol T N} (h : r.output = [x, y]) :
    r.reverse.output = [y, x] := by
  simp [ContextFreeRule.reverse, h]

namespace LeftLinearGrammar

variable {T : Type*}

/-- Reverse every production of a left-linear grammar to obtain a right-linear grammar. -/
def reverseRightLinear (g : LeftLinearGrammar T) : RightLinearGrammar T where
  cfg := g.cfg.reverse
  rightLinear r hr := by
    change ContextFreeRule T g.cfg.NT at r
    change r ∈ g.cfg.rules.map
      ⟨ContextFreeRule.reverse, ContextFreeRule.reverse_injective⟩ at hr
    obtain ⟨source, hsource, rfl⟩ := Finset.mem_map.mp hr
    rcases g.leftLinear source hsource with h | ⟨a, h⟩ | ⟨A, a, h⟩
    · exact Or.inl (ContextFreeRule.reverse_output_nil h)
    · exact Or.inr (Or.inl ⟨a, ContextFreeRule.reverse_output_singleton h⟩)
    · exact Or.inr (Or.inr ⟨a, A, ContextFreeRule.reverse_output_pair h⟩)

/-- Reversing productions reverses the generated language. -/
@[simp] theorem reverseRightLinear_language (g : LeftLinearGrammar T) :
    g.reverseRightLinear.language = g.language.reverse := by
  simp [reverseRightLinear, RightLinearGrammar.language, LeftLinearGrammar.language]

/-- A left-linear grammar with finitely many nonterminals generates a regular language. -/
theorem language_isRegular (g : LeftLinearGrammar T) [Fintype g.cfg.NT] :
    g.language.IsRegular := by
  letI : Fintype g.reverseRightLinear.cfg.NT := by
    change Fintype g.cfg.NT
    infer_instance
  apply Language.isRegular_reverse_iff.mp
  rw [← g.reverseRightLinear_language]
  exact g.reverseRightLinear.language_isRegular

end LeftLinearGrammar

namespace RightLinearGrammar

variable {T : Type*}

/-- Reverse every production of a right-linear grammar to obtain a left-linear grammar. -/
def reverseLeftLinear (g : RightLinearGrammar T) : LeftLinearGrammar T where
  cfg := g.cfg.reverse
  leftLinear r hr := by
    change ContextFreeRule T g.cfg.NT at r
    change r ∈ g.cfg.rules.map
      ⟨ContextFreeRule.reverse, ContextFreeRule.reverse_injective⟩ at hr
    obtain ⟨source, hsource, rfl⟩ := Finset.mem_map.mp hr
    rcases g.rightLinear source hsource with h | ⟨a, h⟩ | ⟨a, B, h⟩
    · exact Or.inl (ContextFreeRule.reverse_output_nil h)
    · exact Or.inr (Or.inl ⟨a, ContextFreeRule.reverse_output_singleton h⟩)
    · exact Or.inr (Or.inr ⟨B, a, ContextFreeRule.reverse_output_pair h⟩)

/-- Reversing productions reverses the generated language. -/
@[simp] theorem reverseLeftLinear_language (g : RightLinearGrammar T) :
    g.reverseLeftLinear.language = g.language.reverse := by
  simp [reverseLeftLinear, LeftLinearGrammar.language, RightLinearGrammar.language]

end RightLinearGrammar

/-- Over finite alphabets, regular languages are exactly the left-linear languages
with a finite nonterminal type: reverse a right-linear witness for the reversed
language back into a left-linear witness for the original language. -/
theorem Language.isRegular_iff_exists_leftLinearGrammar
    {T : Type} [Fintype T] {L : Language T} :
    L.IsRegular ↔
      ∃ g : LeftLinearGrammar T, Nonempty (Fintype g.cfg.NT) ∧ g.language = L := by
  constructor
  · intro hL
    have hrev : L.reverse.IsRegular := Language.isRegular_reverse_iff.mpr hL
    obtain ⟨g, ⟨inst⟩, hg⟩ := Language.isRegular_iff_exists_rightLinearGrammar.mp hrev
    refine ⟨g.reverseLeftLinear, ⟨inst⟩, ?_⟩
    rw [g.reverseLeftLinear_language, hg, Language.reverse_reverse]
  · rintro ⟨g, ⟨inst⟩, rfl⟩
    letI : Fintype g.cfg.NT := inst
    exact g.language_isRegular

end Mathling.Grammar

```

<!--
vim: set filetype=markdown :
Local Variables:
mode: markdown
End:
-->
