module

public import Mathling.Grammar.ContextFree
public import Mathling.Automata.Pushdown

public section

/-!
# Linear grammars

Production-tree semantics and the one-turn NPDA construction for linear grammars.
-/

namespace Mathling.Grammar

namespace LinearGrammar

variable {T : Type*}

/-- The language generated by a linear grammar. -/
def language (g : LinearGrammar T) : Language T := g.cfg.language

end LinearGrammar

namespace LinearGrammar

variable {T : Type*}



private theorem terminals_of_count_eq_zero {N : Type}
    (s : List (Symbol T N))
    (h : s.countP (symbolIsNonterminal (T := T)) = 0) :
    ∃ w : List T, s = terminalSymbols w := by
  induction s with
  | nil => exact ⟨[], rfl⟩
  | cons symbol s ih =>
      cases symbol with
      | terminal a =>
          have hs : s.countP (symbolIsNonterminal (T := T)) = 0 := by
            simpa only [List.countP_cons, symbolIsNonterminal, Bool.false_eq_true, if_false,
              zero_add, Nat.add_zero] using h
          obtain ⟨w, rfl⟩ := ih hs
          exact ⟨a :: w, rfl⟩
      | nonterminal A =>
          simp only [List.countP_cons, symbolIsNonterminal, if_true] at h
          omega

private theorem split_linear_output {N : Type}
    (s : List (Symbol T N))
    (h : s.countP (symbolIsNonterminal (T := T)) ≤ 1) :
    (∃ word : List T, s = terminalSymbols word) ∨
      ∃ pre : List T, ∃ B : N, ∃ suffix : List T,
        s = terminalSymbols pre ++ [Symbol.nonterminal B] ++ terminalSymbols suffix := by
  induction s with
  | nil => exact Or.inl ⟨[], rfl⟩
  | cons symbol s ih =>
      cases symbol with
      | terminal a =>
          have hs : s.countP (symbolIsNonterminal (T := T)) ≤ 1 := by
            simpa only [List.countP_cons, symbolIsNonterminal, Bool.false_eq_true, if_false,
              zero_add, Nat.add_zero] using h
          rcases ih hs with ⟨word, rfl⟩ | ⟨pre, B, suffix, rfl⟩
          · exact Or.inl ⟨a :: word, rfl⟩
          · exact Or.inr ⟨a :: pre, B, suffix, by simp [terminalSymbols]⟩
      | nonterminal A =>
          have hc : s.countP (symbolIsNonterminal (T := T)) + 1 ≤ 1 := by
            simpa only [List.countP_cons, symbolIsNonterminal, if_true] using h
          have hz : s.countP (symbolIsNonterminal (T := T)) = 0 := by omega
          obtain ⟨suffix, rfl⟩ := terminals_of_count_eq_zero s hz
          exact Or.inr ⟨[], A, suffix, by simp [terminalSymbols]⟩

/-- The production-tree semantics of a linear grammar. -/
inductive LinearGenerates (g : LinearGrammar T) : g.cfg.NT → List T → Prop
  | leaf {r : ContextFreeRule T g.cfg.NT} {word : List T}
      (hr : r ∈ g.cfg.rules) (hout : r.output = terminalSymbols word) :
      LinearGenerates g r.input word
  | branch {r : ContextFreeRule T g.cfg.NT} {pre suffix middle : List T}
      {B : g.cfg.NT}
      (hr : r ∈ g.cfg.rules)
      (hout : r.output =
        terminalSymbols pre ++ [Symbol.nonterminal B] ++ terminalSymbols suffix)
      (child : LinearGenerates g B middle) :
      LinearGenerates g r.input (pre ++ middle ++ suffix)

private theorem generates_derives (g : LinearGrammar T)
    {A : g.cfg.NT} {w : List T} (h : LinearGenerates g A w) :
    g.cfg.Derives [Symbol.nonterminal A] (terminalSymbols w) := by
  induction h with
  | leaf hr hout =>
      have hp : g.cfg.Produces [Symbol.nonterminal _] _ :=
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩
      simpa [hout] using hp.single
  | @branch r pre suffix middle B hr hout child ih =>
      have hp : g.cfg.Produces [Symbol.nonterminal _] _ :=
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩
      apply hp.single.trans
      have hctx := (ih.append_left (terminalSymbols pre)).append_right
        (terminalSymbols suffix)
      simpa [hout, terminalSymbols, List.map_append, List.append_assoc] using hctx


private theorem rewrites_terminal_context (r : ContextFreeRule T N)
    (left right : List T) (A : N) {v : List (Symbol T N)}
    (h : r.Rewrites
      (terminalSymbols left ++ [Symbol.nonterminal A] ++ terminalSymbols right) v) :
    r.input = A ∧
      v = terminalSymbols left ++ r.output ++ terminalSymbols right := by
  induction left generalizing v with
  | nil =>
      simp only [terminalSymbols, List.map_nil, List.nil_append] at h ⊢
      cases h with
      | head s => exact ⟨rfl, rfl⟩
      | cons _ htail =>
          exact (ContextFreeGrammar.no_rewrites_terminals r htail).elim
  | cons a left ih =>
      simp only [terminalSymbols, List.map_cons, List.cons_append] at h ⊢
      cases h with
      | cons _ htail =>
          obtain ⟨hin, hout⟩ := ih htail
          exact ⟨hin, congrArg (Symbol.terminal a :: ·) hout⟩


private theorem derives_linear_context (g : LinearGrammar T)
    {form : List (Symbol T g.cfg.NT)} {target : List T}
    (h : g.cfg.Derives form (terminalSymbols target)) :
    ∀ (left right : List T) (A : g.cfg.NT),
      form = terminalSymbols left ++ [Symbol.nonterminal A] ++ terminalSymbols right →
      ∃ middle : List T,
        target = left ++ middle ++ right ∧ LinearGenerates g A middle := by
  induction h using Relation.ReflTransGen.head_induction_on with
  | refl =>
      intro left right A hform
      have hmem : Symbol.nonterminal A ∈ terminalSymbols target := by
        rw [hform]
        simp
      simp [terminalSymbols] at hmem
  | head hprod hrest ih =>
      intro left right A hform
      rcases hprod with ⟨r, hr, hw⟩
      rw [hform] at hw
      obtain ⟨hin, hc⟩ := rewrites_terminal_context r left right A hw
      cases hin
      have hcount : r.output.countP (symbolIsNonterminal (T := T)) ≤ 1 :=
        g.linear r hr
      rcases split_linear_output r.output hcount with
        ⟨word, hout⟩ | ⟨pre, B, suffix, hout⟩
      · have hrest' :
            g.cfg.Derives
              (terminalSymbols left ++ r.output ++ terminalSymbols right)
              (terminalSymbols target) := by
          rw [← hc]
          exact hrest
        have hterminal :
            g.cfg.Derives (terminalSymbols (left ++ word ++ right))
              (terminalSymbols target) := by
          rw [hout] at hrest'
          simpa [terminalSymbols, List.map_append, List.append_assoc] using hrest'
        refine ⟨word,
          (ContextFreeGrammar.derives_terminals_eq g.cfg hterminal).symm, ?_⟩
        exact LinearGenerates.leaf hr hout
      · obtain ⟨middle, heq, hmiddle⟩ :=
          ih (left ++ pre) (suffix ++ right) B (by
            rw [hc, hout]
            simp [terminalSymbols, List.map_append, List.append_assoc])
        refine ⟨pre ++ middle ++ suffix, ?_, ?_⟩
        · simpa [List.append_assoc] using heq
        · exact LinearGenerates.branch hr hout hmiddle

/-- Production trees and context-free derivations agree for linear grammars. -/
theorem linearGenerates_iff (g : LinearGrammar T) (w : List T) :
    LinearGenerates g g.cfg.initial w ↔ w ∈ g.language := by
  constructor
  · exact generates_derives g
  · intro h
    obtain ⟨middle, heq, hmiddle⟩ :=
      derives_linear_context g h [] [] g.cfg.initial rfl
    simp only [List.nil_append, List.append_nil] at heq
    subst middle
    exact hmiddle

/-- Control states for the production-driven linear-grammar PDA. -/
inductive LinearPDAState (g : LinearGrammar T) where
  | derive (A : g.cfg.NT)
  | prefixLeaf (r : ContextFreeRule T g.cfg.NT) (hr : r ∈ g.cfg.rules)
      (word todo : List T) (hout : r.output = terminalSymbols word)
  | prefixBranch (r : ContextFreeRule T g.cfg.NT) (hr : r ∈ g.cfg.rules)
      (pre todo : List T) (B : g.cfg.NT) (suffix : List T)
      (hout : r.output =
        terminalSymbols pre ++ [Symbol.nonterminal B] ++ terminalSymbols suffix)
  | pushBranch (B : g.cfg.NT) (suffix todo : List T)
  | matchStack
  | finished

/-- Local micro-transitions for the linear-grammar PDA. -/
private inductive LinearRawStep (g : LinearGrammar T) :
    LinearPDAState g → Mathling.Automata.TurnPhase → Option T → List T →
      LinearPDAState g → Mathling.Automata.TurnPhase → List T → Prop
  | chooseLeaf {r word stack}
      (hr : r ∈ g.cfg.rules) (hout : r.output = terminalSymbols word) :
      LinearRawStep g (.derive r.input) .push none stack
        (.prefixLeaf r hr word word hout) .push stack
  | chooseBranch {r pre B suffix stack}
      (hr : r ∈ g.cfg.rules)
      (hout : r.output =
        terminalSymbols pre ++ [Symbol.nonterminal B] ++ terminalSymbols suffix) :
      LinearRawStep g (.derive r.input) .push none stack
        (.prefixBranch r hr pre pre B suffix hout) .push stack
  | consumeLeaf {r hr word a todo hout stack} :
      LinearRawStep g (.prefixLeaf r hr word (a :: todo) hout) .push
        (some a) stack (.prefixLeaf r hr word todo hout) .push stack
  | consumeBranch {r hr pre a todo B suffix hout stack} :
      LinearRawStep g (.prefixBranch r hr pre (a :: todo) B suffix hout) .push
        (some a) stack (.prefixBranch r hr pre todo B suffix hout) .push stack
  | finishLeaf {r hr word hout stack} :
      LinearRawStep g (.prefixLeaf r hr word [] hout) .push none stack
        .matchStack .pop stack
  | beginPush {r hr pre B suffix hout stack} :
      LinearRawStep g (.prefixBranch r hr pre [] B suffix hout) .push none stack
        (.pushBranch B suffix suffix.reverse) .push stack
  | push {B suffix a todo stack} :
      LinearRawStep g (.pushBranch B suffix (a :: todo)) .push none stack
        (.pushBranch B suffix todo) .push (a :: stack)
  | continue {B suffix stack} :
      LinearRawStep g (.pushBranch B suffix []) .push none stack
        (.derive B) .push stack
  | matchStack {a stack} :
      LinearRawStep g .matchStack .pop (some a) (a :: stack)
        .matchStack .pop stack
  | finish :
      LinearRawStep g .matchStack .pop none [] .finished .pop []

/-- Convert a linear grammar to a local, production-driven one-turn NPDA. -/
def toOneTurnNPDA (g : LinearGrammar T) :
    Mathling.Automata.OneTurnNPDA T (LinearPDAState g) T where
  step q phase sym stack :=
    {next | LinearRawStep g q phase sym stack next.1 next.2.1 next.2.2}
  start := {.derive g.cfg.initial}
  accept := {.finished}
  initialStack := []
  pop_stays_pop := by
    intro q p sym stack q' p' stack' h hp
    cases h <;> simp_all
  push_phase_nonshrinking := by
    intro q sym stack q' stack' h
    cases h <;> simp
  pop_phase_nongrowing := by
    intro q p sym stack q' stack' h
    cases h <;> simp

private theorem consumeLeaf_reaches (g : LinearGrammar T)
    {r : ContextFreeRule T g.cfg.NT} {hr : r ∈ g.cfg.rules}
    {word : List T} {hout : r.output = terminalSymbols word}
    (todo rest stack : List T) :
    g.toOneTurnNPDA.toNPDA.Reaches
      (todo ++ rest, (.prefixLeaf r hr word todo hout, .push), stack)
      (rest, (.prefixLeaf r hr word [] hout, .push), stack) := by
  induction todo with
  | nil => exact Relation.ReflTransGen.refl
  | cons a todo ih =>
      have hstep : g.toOneTurnNPDA.toNPDA.Step
          (a :: todo ++ rest, (.prefixLeaf r hr word (a :: todo) hout, .push), stack)
          (todo ++ rest, (.prefixLeaf r hr word todo hout, .push), stack) := by
        apply Mathling.Automata.NPDA.Step.consume
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.consumeLeaf
      exact ih.head hstep

private theorem consumeBranch_reaches (g : LinearGrammar T)
    {r : ContextFreeRule T g.cfg.NT} {hr : r ∈ g.cfg.rules}
    {pre : List T} {B : g.cfg.NT} {suffix : List T}
    {hout : r.output =
      terminalSymbols pre ++ [Symbol.nonterminal B] ++ terminalSymbols suffix}
    (todo rest stack : List T) :
    g.toOneTurnNPDA.toNPDA.Reaches
      (todo ++ rest, (.prefixBranch r hr pre todo B suffix hout, .push), stack)
      (rest, (.prefixBranch r hr pre [] B suffix hout, .push), stack) := by
  induction todo with
  | nil => exact Relation.ReflTransGen.refl
  | cons a todo ih =>
      have hstep : g.toOneTurnNPDA.toNPDA.Step
          (a :: todo ++ rest,
            (.prefixBranch r hr pre (a :: todo) B suffix hout, .push), stack)
          (todo ++ rest, (.prefixBranch r hr pre todo B suffix hout, .push), stack) := by
        apply Mathling.Automata.NPDA.Step.consume
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.consumeBranch
      exact ih.head hstep

private theorem pushBranch_reaches (g : LinearGrammar T) (B : g.cfg.NT)
    (suffix todo input stack : List T) :
    g.toOneTurnNPDA.toNPDA.Reaches
      (input, (.pushBranch B suffix todo, .push), stack)
      (input, (.derive B, .push), todo.reverse ++ stack) := by
  induction todo generalizing stack with
  | nil =>
      apply Relation.ReflTransGen.single
      apply Mathling.Automata.NPDA.Step.epsilon
      change LinearRawStep g _ _ _ _ _ _ _
      exact LinearRawStep.continue
  | cons a todo ih =>
      have hstep : g.toOneTurnNPDA.toNPDA.Step
          (input, (.pushBranch B suffix (a :: todo), .push), stack)
          (input, (.pushBranch B suffix todo, .push), a :: stack) := by
        apply Mathling.Automata.NPDA.Step.epsilon
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.push
      have hrest' : g.toOneTurnNPDA.toNPDA.Reaches
          (input, (.pushBranch B suffix todo, .push), a :: stack)
          (input, (.derive B, .push), (a :: todo).reverse ++ stack) := by
        simpa [List.reverse_cons, List.append_assoc] using ih (a :: stack)
      exact hrest'.head hstep

private theorem matchStack_reaches (g : LinearGrammar T) (stack : List T) :
    g.toOneTurnNPDA.toNPDA.Reaches
      (stack, (.matchStack, .pop), stack)
      ([], (.finished, .pop), []) := by
  induction stack with
  | nil =>
      apply Relation.ReflTransGen.single
      apply Mathling.Automata.NPDA.Step.epsilon
      change LinearRawStep g _ _ _ _ _ _ _
      exact LinearRawStep.finish
  | cons a stack ih =>
      have hstep : g.toOneTurnNPDA.toNPDA.Step
          (a :: stack, (.matchStack, .pop), a :: stack)
          (stack, (.matchStack, .pop), stack) := by
        apply Mathling.Automata.NPDA.Step.consume
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.matchStack
      exact ih.head hstep

private theorem generates_reaches (g : LinearGrammar T)
    {A : g.cfg.NT} {word : List T} (h : LinearGenerates g A word)
    (stack : List T) :
    g.toOneTurnNPDA.toNPDA.Reaches
      (word ++ stack, (.derive A, .push), stack)
      ([], (.finished, .pop), []) := by
  induction h generalizing stack with
  | @leaf r word hr hout =>
      have hchoose : g.toOneTurnNPDA.toNPDA.Step
          (word ++ stack, (.derive r.input, .push), stack)
          (word ++ stack, (.prefixLeaf r hr word word hout, .push), stack) := by
        apply Mathling.Automata.NPDA.Step.epsilon
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.chooseLeaf hr hout
      have hconsume := consumeLeaf_reaches g (r := r) (hr := hr)
        (word := word) (hout := hout) word stack stack
      have hpop : g.toOneTurnNPDA.toNPDA.Step
          (stack, (.prefixLeaf r hr word [] hout, .push), stack)
          (stack, (.matchStack, .pop), stack) := by
        apply Mathling.Automata.NPDA.Step.epsilon
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.finishLeaf
      exact ((Relation.ReflTransGen.single hchoose).trans hconsume).tail hpop
        |>.trans (matchStack_reaches g stack)
  | @branch r pre suffix middle B hr hout child ih =>
      have hchoose : g.toOneTurnNPDA.toNPDA.Step
          ((pre ++ middle ++ suffix) ++ stack, (.derive r.input, .push), stack)
          ((pre ++ middle ++ suffix) ++ stack,
            (.prefixBranch r hr pre pre B suffix hout, .push), stack) := by
        apply Mathling.Automata.NPDA.Step.epsilon
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.chooseBranch hr hout
      have hconsume := consumeBranch_reaches g (r := r) (hr := hr)
        (pre := pre) (B := B) (suffix := suffix) (hout := hout)
        pre (middle ++ suffix ++ stack) stack
      have hbegin : g.toOneTurnNPDA.toNPDA.Step
          (middle ++ suffix ++ stack,
            (.prefixBranch r hr pre [] B suffix hout, .push), stack)
          (middle ++ suffix ++ stack,
            (.pushBranch B suffix suffix.reverse, .push), stack) := by
        apply Mathling.Automata.NPDA.Step.epsilon
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.beginPush
      have hpush := pushBranch_reaches g B suffix suffix.reverse
        (middle ++ suffix ++ stack) stack
      have hpush' : g.toOneTurnNPDA.toNPDA.Reaches
          (middle ++ suffix ++ stack,
            (.pushBranch B suffix suffix.reverse, .push), stack)
          (middle ++ suffix ++ stack, (.derive B, .push), suffix ++ stack) := by
        simpa using hpush
      have hchild := ih (suffix ++ stack)
      exact ((Relation.ReflTransGen.single hchoose).trans
        (by simpa [List.append_assoc] using hconsume)).tail hbegin
        |>.trans hpush' |>.trans (by simpa [List.append_assoc] using hchild)

private def LinearGood (g : LinearGrammar T) :
    Mathling.Automata.NPDA.ID T
      (LinearPDAState g × Mathling.Automata.TurnPhase) T → Prop
  | (input, (.derive A, .push), stack) =>
      ∃ word, input = word ++ stack ∧ LinearGenerates g A word
  | (input, (.prefixLeaf _ _ _ todo _, .push), stack) =>
      input = todo ++ stack
  | (input, (.prefixBranch _ _ _ todo B suffix _, .push), stack) =>
      ∃ middle, LinearGenerates g B middle ∧
        input = todo ++ middle ++ suffix ++ stack
  | (input, (.pushBranch B _ todo, .push), stack) =>
      ∃ middle, LinearGenerates g B middle ∧
        input = middle ++ todo.reverse ++ stack
  | (input, (.matchStack, .pop), stack) => input = stack
  | (input, (.finished, _), _) => input = []
  | _ => False

private theorem raw_step_good (g : LinearGrammar T)
    {q q' : LinearPDAState g} {p p' : Mathling.Automata.TurnPhase}
    {sym : Option T} {stack stack' : List T}
    (h : LinearRawStep g q p sym stack q' p' stack') (input : List T) :
    LinearGood g (input, (q', p'), stack') →
      LinearGood g
        ((match sym with | none => input | some a => a :: input), (q, p), stack) := by
  cases h with
  | @chooseLeaf r word stack hr hout =>
      intro hinput
      exact ⟨word, hinput, LinearGenerates.leaf hr hout⟩
  | @chooseBranch r pre B suffix stack hr hout =>
      rintro ⟨middle, hmiddle, hinput⟩
      refine ⟨pre ++ middle ++ suffix, ?_, LinearGenerates.branch hr hout hmiddle⟩
      simpa [List.append_assoc] using hinput
  | consumeLeaf =>
      simp [LinearGood]
  | consumeBranch =>
      simp [LinearGood, List.append_assoc]
  | finishLeaf =>
      simp [LinearGood]
  | beginPush =>
      simp [LinearGood, List.append_assoc]
  | push =>
      simp [LinearGood, List.reverse_cons, List.append_assoc]
  | «continue» =>
      rintro ⟨middle, hinput, hmiddle⟩
      exact ⟨middle, hmiddle, by simpa using hinput⟩
  | matchStack =>
      simp [LinearGood]
  | finish =>
      simp [LinearGood]

private theorem step_good (g : LinearGrammar T)
    {c c' : Mathling.Automata.NPDA.ID T
      (LinearPDAState g × Mathling.Automata.TurnPhase) T}
    (h : g.toOneTurnNPDA.toNPDA.Step c c') :
    LinearGood g c' → LinearGood g c := by
  cases h with
  | consume hraw =>
      change LinearRawStep g _ _ _ _ _ _ _ at hraw
      exact raw_step_good g hraw _
  | epsilon hraw =>
      change LinearRawStep g _ _ _ _ _ _ _ at hraw
      exact raw_step_good g hraw _

private theorem reaches_good (g : LinearGrammar T)
    {c c' : Mathling.Automata.NPDA.ID T
      (LinearPDAState g × Mathling.Automata.TurnPhase) T}
    (h : g.toOneTurnNPDA.toNPDA.Reaches c c') :
    LinearGood g c' → LinearGood g c := by
  induction h using Relation.ReflTransGen.head_induction_on with
  | refl => exact id
  | head hstep _ ih =>
      intro hgood
      exact step_good g hstep (ih hgood)

/-- The local one-turn PDA accepts exactly the language generated by the linear grammar. -/
@[simp] theorem toOneTurnNPDA_language (g : LinearGrammar T) :
    g.toOneTurnNPDA.language = g.language := by
  ext input
  constructor
  · intro hinput
    change g.toOneTurnNPDA.toNPDA.Accepts input at hinput
    rcases hinput with ⟨⟨start, phase⟩, hstart,
      ⟨final, finalPhase⟩, hfinal, stack, hreach⟩
    change start ∈ g.toOneTurnNPDA.start ∧ phase = .push at hstart
    rcases hstart with ⟨hstart, rfl⟩
    change start ∈ ({.derive g.cfg.initial} : Set (LinearPDAState g)) at hstart
    simp only [Set.mem_singleton_iff] at hstart
    subst start
    change final ∈ g.toOneTurnNPDA.accept at hfinal
    change final ∈ ({.finished} : Set (LinearPDAState g)) at hfinal
    simp only [Set.mem_singleton_iff] at hfinal
    subst final
    have hgood : LinearGood g
        (input, (.derive g.cfg.initial, .push), []) :=
      reaches_good g hreach (by simp [LinearGood])
    rcases hgood with ⟨word, hword, hgenerates⟩
    simp only [List.append_nil] at hword
    subst input
    exact (linearGenerates_iff g word).mp hgenerates
  · intro hinput
    have hgenerates := (linearGenerates_iff g input).mpr hinput
    change g.toOneTurnNPDA.toNPDA.Accepts input
    refine ⟨(.derive g.cfg.initial, .push), ?_,
      (.finished, .pop), ?_, [], ?_⟩
    · exact ⟨by simp [toOneTurnNPDA], rfl⟩
    · simp [Mathling.Automata.OneTurnNPDA.toNPDA, toOneTurnNPDA]
    · simpa [Mathling.Automata.OneTurnNPDA.toNPDA, toOneTurnNPDA] using
        generates_reaches g hgenerates []

end LinearGrammar

end Mathling.Grammar
