module

public import Mathling.Grammar.Core
public import Mathling.Automata.Core
public import Mathlib.Data.Fintype.Option

public section

/-!
# Right-linear grammars

Right-linear grammars, their NFA construction, and the DFA correspondence.
-/

namespace Mathling.Grammar
open Mathling.Automata


namespace RightLinearGrammar

variable {T : Type*}

/-- The language generated by a right-linear grammar. -/
@[expose] def language (g : RightLinearGrammar T) : Language T := g.cfg.language

/-- Forget that a right-linear grammar is right-linear. -/
def toLinear (g : RightLinearGrammar T) : LinearGrammar T where
  cfg := g.cfg
  linear r hr := by
    rcases g.rightLinear r hr with h | ⟨a, h⟩ | ⟨a, B, h⟩ <;>
      simp [ContextFreeRule.IsLinear, ContextFreeRule.nonterminalCount,
        symbolIsNonterminal, h]

/-- Convert a right-linear grammar to an NFA with a final sink state. -/
def toNFA (g : RightLinearGrammar T) : Mathling.Automata.NFA T (Option g.cfg.NT) where
  step q a := {q' |
    ∃ A, q = some A ∧
      ((q' = none ∧
          ({ input := A, output := [Symbol.terminal a] } :
            ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules) ∨
        ∃ B, q' = some B ∧
          ({ input := A, output := [Symbol.terminal a, Symbol.nonterminal B] } :
            ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules)}
  start := {some g.cfg.initial}
  accept := {q |
    q = none ∨ ∃ A, q = some A ∧
      ({ input := A, output := [] } : ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules}

private inductive GeneratesFrom (g : RightLinearGrammar T) :
    g.cfg.NT → List T → Prop
  | epsilon {A}
      (h : ({ input := A, output := [] } : ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules) :
      GeneratesFrom g A []
  | terminal {A a}
      (h : ({ input := A, output := [Symbol.terminal a] } :
        ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules) :
      GeneratesFrom g A [a]
  | step {A a B w}
      (h : ({ input := A, output := [Symbol.terminal a, Symbol.nonterminal B] } :
        ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules)
      (tail : GeneratesFrom g B w) :
      GeneratesFrom g A (a :: w)

private theorem rewrites_singleton_nonterminal
    {r : ContextFreeRule T N} {A : N} {v : List (Symbol T N)}
    (h : r.Rewrites [Symbol.nonterminal A] v) :
    r.input = A ∧ v = r.output := by
  cases h with
  | head s => exact ⟨rfl, by simp⟩
  | cons _ htail => cases htail

private theorem rule_mem_of_output_eq
    {g : ContextFreeGrammar T} {r : ContextFreeRule T g.NT}
    (hr : r ∈ g.rules) {output : List (Symbol T g.NT)}
    (hout : r.output = output) :
    ({ input := r.input, output } : ContextFreeRule T g.NT) ∈ g.rules := by
  have heq : ({ input := r.input, output } : ContextFreeRule T g.NT) = r := by
    apply ContextFreeRule.ext
    · rfl
    · exact hout.symm
  simpa only [heq] using hr

private theorem produces_terminal_cons
    {g : ContextFreeGrammar T} {a : T} {u v : List (Symbol T g.NT)}
    (h : g.Produces (Symbol.terminal a :: u) v) :
    ∃ v', v = Symbol.terminal a :: v' ∧ g.Produces u v' := by
  obtain ⟨r, hr, hw⟩ := h
  cases hw with
  | cons _ htail => exact ⟨_, rfl, ⟨r, hr, htail⟩⟩

private theorem derives_terminal_cons
    {g : ContextFreeGrammar T} {a : T} {u v : List (Symbol T g.NT)}
    (h : g.Derives (Symbol.terminal a :: u) v) :
    ∃ v', v = Symbol.terminal a :: v' ∧ g.Derives u v' := by
  induction h with
  | refl => exact ⟨u, rfl, .refl u⟩
  | tail hreach hprod ih =>
      obtain ⟨mid, rfl, htail⟩ := ih
      obtain ⟨v', rfl, hstep⟩ := produces_terminal_cons hprod
      exact ⟨v', rfl, htail.trans_produces hstep⟩

private theorem derives_nil_eq
    {g : ContextFreeGrammar T} {v : List (Symbol T g.NT)}
    (h : g.Derives [] v) : v = [] := by
  induction h with
  | refl => rfl
  | tail _ hprod ih =>
      subst ih
      obtain ⟨r, _, hw⟩ := hprod
      cases hw

private theorem generatesFrom_derives (g : RightLinearGrammar T)
    {A : g.cfg.NT} {w : List T} (h : GeneratesFrom g A w) :
    g.cfg.Derives [Symbol.nonterminal A] (w.map Symbol.terminal) := by
  induction h with
  | epsilon hr =>
      exact ContextFreeGrammar.Produces.single
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩
  | terminal hr =>
      exact ContextFreeGrammar.Produces.single
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩
  | step hr _ ih =>
      exact (ContextFreeGrammar.Produces.single
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩).trans
          (ih.append_left [Symbol.terminal _])

private theorem derives_generatesFrom (g : RightLinearGrammar T)
    {A : g.cfg.NT} {w : List T}
    (h : g.cfg.Derives [Symbol.nonterminal A] (w.map Symbol.terminal)) :
    GeneratesFrom g A w := by
  rcases h.eq_or_head with heq | ⟨v, hprod, hrest⟩
  · cases w <;> simp at heq
  · obtain ⟨r, hr, hw⟩ := hprod
    obtain ⟨rfl, rfl⟩ := rewrites_singleton_nonterminal hw
    rcases g.rightLinear r hr with hout | ⟨a, hout⟩ | ⟨a, B, hout⟩
    · rw [hout] at hrest
      have hε : ({ input := r.input, output := [] } :
          ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules :=
        rule_mem_of_output_eq hr hout
      have hwNil : w.map Symbol.terminal = [] := derives_nil_eq hrest
      have : w = [] := by
        cases w with
        | nil => rfl
        | cons => simp at hwNil
      subst this
      exact .epsilon hε
    · rw [hout] at hrest
      have hterminal : ({ input := r.input, output := [Symbol.terminal a] } :
          ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules :=
        rule_mem_of_output_eq hr hout
      obtain ⟨tail, htail, hder⟩ := derives_terminal_cons hrest
      have hnil := derives_nil_eq hder
      subst hnil
      cases w with
      | nil => simp at htail
      | cons b ws =>
          simp only [List.map_cons, List.cons.injEq, Symbol.terminal.injEq,
            List.map_eq_nil_iff] at htail
          obtain ⟨rfl, rfl⟩ := htail
          exact .terminal hterminal
    · rw [hout] at hrest
      have hstep :
          ({ input := r.input,
             output := [Symbol.terminal a, Symbol.nonterminal B] } :
            ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules :=
        rule_mem_of_output_eq hr hout
      obtain ⟨tail, htail, hder⟩ := derives_terminal_cons hrest
      cases w with
      | nil => simp at htail
      | cons b ws =>
          simp only [List.map_cons, List.cons.injEq, Symbol.terminal.injEq] at htail
          obtain ⟨rfl, rfl⟩ := htail
          exact .step hstep (derives_generatesFrom g hder)
termination_by w.length

private theorem generatesFrom_path (g : RightLinearGrammar T)
    {A : g.cfg.NT} {w : List T} (h : GeneratesFrom g A w) :
    ∃ q ∈ g.toNFA.accept, Nonempty (g.toNFA.Path (some A) q w) := by
  induction h with
  | epsilon hr =>
      exact ⟨some _, by
        exact Or.inr ⟨_, rfl, hr⟩, ⟨.nil _⟩⟩
  | terminal hr =>
      exact ⟨none, Or.inl rfl,
        ⟨.cons none (some _) none _ [] ⟨_, rfl, Or.inl ⟨rfl, hr⟩⟩ (.nil none)⟩⟩
  | step hr _ ih =>
      obtain ⟨q, hq, ⟨path⟩⟩ := ih
      exact ⟨q, hq,
        ⟨.cons (some _) (some _) q _ _ ⟨_, rfl, Or.inr ⟨_, rfl, hr⟩⟩ path⟩⟩

private theorem path_accept_generatesFrom (g : RightLinearGrammar T)
    {A : g.cfg.NT} {start q : Option g.cfg.NT} {w : List T}
    (p : g.toNFA.Path start q w) (hstart : start = some A)
    (hq : q ∈ g.toNFA.accept) :
    GeneratesFrom g A w := by
  induction p generalizing A with
  | nil state =>
      cases hstart
      rcases hq with hnone | ⟨B, hsome, hr⟩
      · contradiction
      · cases hsome
        exact .epsilon hr
  | cons next start final a tail hedge path ih =>
      cases hstart
      rcases hedge with ⟨B, hsome, hfinal | hnext⟩
      · cases hsome
        obtain ⟨rfl, hr⟩ := hfinal
        cases path with
        | nil => exact .terminal hr
        | cons next' _ _ a' tail' hedge' path' =>
            simp [toNFA] at hedge'
      · cases hsome
        obtain ⟨C, rfl, hr⟩ := hnext
        exact .step hr (ih rfl hq)

/-- The NFA construction accepts exactly the grammar's language. -/
@[simp] theorem toNFA_language (g : RightLinearGrammar T) :
    g.toNFA.accepts = g.language := by
  ext w
  rw [_root_.NFA.accepts_iff_exists_path]
  constructor
  · rintro ⟨q, hstart, q', haccept, ⟨path⟩⟩
    have hq : q = some g.cfg.initial := hstart
    subst q
    exact generatesFrom_derives g (path_accept_generatesFrom g path rfl haccept)
  · intro h
    have hgen : GeneratesFrom g g.cfg.initial w :=
      derives_generatesFrom g h
    obtain ⟨q, hq, ⟨path⟩⟩ := generatesFrom_path g hgen
    exact ⟨some g.cfg.initial, rfl, q, hq, ⟨path⟩⟩

/-- A right-linear grammar with finitely many nonterminals generates a regular language. -/
theorem language_isRegular (g : RightLinearGrammar T) [Fintype g.cfg.NT] :
    g.language.IsRegular := by
  apply Language.isRegular_iff_nfa.mpr
  exact ⟨Option g.cfg.NT, inferInstance, g.toNFA, g.toNFA_language⟩

end RightLinearGrammar

end Mathling.Grammar

namespace Mathling.Automata.DFA

open Mathling.Grammar

variable {T : Type*} {σ : Type}

private def transitionRule (M : Mathling.Automata.DFA T σ) (qa : σ × T) :
    ContextFreeRule T σ :=
  { input := qa.1
    output := [Symbol.terminal qa.2, Symbol.nonterminal (M.step qa.1 qa.2)] }

private def acceptingRule (q : σ) : ContextFreeRule T σ :=
  { input := q, output := [] }

private def dfaRules [Fintype T] [Fintype σ]
    [DecidableEq T] [DecidableEq σ] (M : Mathling.Automata.DFA T σ)
    [DecidablePred (· ∈ M.accept)] : Finset (ContextFreeRule T σ) :=
  (Finset.univ.product Finset.univ).image (transitionRule M) ∪
    (Finset.univ.filter fun q => q ∈ M.accept).image acceptingRule

/-- Convert a finite DFA to a right-linear grammar. -/
def toRightLinearGrammar [Fintype T] [Fintype σ]
    [DecidableEq T] [DecidableEq σ] (M : Mathling.Automata.DFA T σ)
    [DecidablePred (· ∈ M.accept)] : RightLinearGrammar T :=
  { cfg :=
      { NT := σ
        initial := M.start
        rules := dfaRules M }
    rightLinear := by
      classical
      intro r hr
      change r ∈
        (Finset.univ.product Finset.univ).image (transitionRule M) ∪
          (Finset.univ.filter fun q => q ∈ M.accept).image acceptingRule at hr
      rw [Finset.mem_union, Finset.mem_image, Finset.mem_image] at hr
      rcases hr with ⟨qa, _, rfl⟩ | ⟨q, hq, rfl⟩
      · exact Or.inr (Or.inr ⟨qa.2, M.step qa.1 qa.2, rfl⟩)
      · exact Or.inl rfl }

private theorem mem_dfaRules [Fintype T] [Fintype σ]
    [DecidableEq T] [DecidableEq σ] (M : Mathling.Automata.DFA T σ)
    [DecidablePred (· ∈ M.accept)] (r : ContextFreeRule T σ) :
    r ∈ dfaRules M ↔
      (∃ qa : σ × T, transitionRule M qa = r) ∨
      ∃ q ∈ M.accept, acceptingRule q = r := by
  classical
  change r ∈
    (Finset.univ.product Finset.univ).image (transitionRule M) ∪
    (Finset.univ.filter fun q => q ∈ M.accept).image acceptingRule ↔ _
  rw [Finset.mem_union, Finset.mem_image, Finset.mem_image]
  constructor
  · rintro (⟨qa, _, hqa⟩ | ⟨q, hq, hqr⟩)
    · exact Or.inl ⟨qa, hqa⟩
    · exact Or.inr ⟨q, (Finset.mem_filter.mp hq).2, hqr⟩
  · rintro (⟨qa, hqa⟩ | ⟨q, hq, hqr⟩)
    · exact Or.inl ⟨qa, by simp, hqa⟩
    · exact Or.inr ⟨q, Finset.mem_filter.mpr ⟨by simp, hq⟩, hqr⟩

private theorem generatesFrom_dfa_accept
    (g : RightLinearGrammar T) (M : Mathling.Automata.DFA T σ)
    (encode : g.cfg.NT → σ)
    (hε : ∀ A, ({ input := A, output := [] } :
      ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules → encode A ∈ M.accept)
    (hterminal : ∀ A a, ({ input := A, output := [Symbol.terminal a] } :
      ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules → False)
    (hstep : ∀ A a B,
      ({ input := A, output := [Symbol.terminal a, Symbol.nonterminal B] } :
        ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules →
      encode B = M.step (encode A) a)
    {A : g.cfg.NT} {w : List T} (h : RightLinearGrammar.GeneratesFrom g A w) :
    M.evalFrom (encode A) w ∈ M.accept := by
  induction h with
  | epsilon hr => simpa using hε _ hr
  | terminal hr => exact (hterminal _ _ hr).elim
  | step hr _ ih =>
      rw [DFA.evalFrom_cons, ← hstep _ _ _ hr]
      exact ih

private theorem generatesFrom_toRightLinearGrammar_iff
    [Fintype T] [Fintype σ] [DecidableEq T] [DecidableEq σ]
    (M : Mathling.Automata.DFA T σ) [DecidablePred (· ∈ M.accept)]
    (q : σ) (w : List T) :
    RightLinearGrammar.GeneratesFrom (toRightLinearGrammar M) q w ↔
      M.evalFrom q w ∈ M.accept := by
  classical
  constructor
  · intro h
    apply generatesFrom_dfa_accept (toRightLinearGrammar M) M id
    · intro A hr
      change σ at A
      change acceptingRule A ∈ dfaRules M at hr
      simpa [mem_dfaRules, acceptingRule, transitionRule] using hr
    · intro A a hr
      change σ at A
      change ({ input := A, output := [Symbol.terminal a] } :
        ContextFreeRule T σ) ∈ dfaRules M at hr
      simp [mem_dfaRules, acceptingRule, transitionRule] at hr
    · intro A a B hr
      change σ at A B
      change ({ input := A, output := [Symbol.terminal a, Symbol.nonterminal B] } :
        ContextFreeRule T σ) ∈ dfaRules M at hr
      have h := hr
      simp [mem_dfaRules, transitionRule, acceptingRule] at h
      exact h.symm
    · exact h
  · induction w generalizing q with
    | nil =>
        intro hq
        apply RightLinearGrammar.GeneratesFrom.epsilon
        change acceptingRule q ∈ dfaRules M
        rw [mem_dfaRules]
        exact Or.inr ⟨q, hq, rfl⟩
    | cons a tail ih =>
        intro hq
        apply RightLinearGrammar.GeneratesFrom.step (B := M.step q a)
        · change transitionRule M (q, a) ∈ dfaRules M
          simp [mem_dfaRules]
        · exact ih (M.step q a) (by simpa using hq)

/-- The grammar constructed from a finite DFA generates exactly its language. -/
@[simp] theorem toRightLinearGrammar_language [Fintype T] [Fintype σ]
    [DecidableEq T] [DecidableEq σ] (M : Mathling.Automata.DFA T σ)
    [DecidablePred (· ∈ M.accept)] :
    (toRightLinearGrammar M).language = M.accepts := by
  ext w
  change (toRightLinearGrammar M).cfg.Derives
    [Symbol.nonterminal M.start] (w.map Symbol.terminal) ↔
      M.evalFrom M.start w ∈ M.accept
  rw [← generatesFrom_toRightLinearGrammar_iff M M.start w]
  exact ⟨RightLinearGrammar.derives_generatesFrom (toRightLinearGrammar M),
    RightLinearGrammar.generatesFrom_derives (toRightLinearGrammar M)⟩

end Mathling.Automata.DFA

namespace Mathling.Grammar

/-- Over finite alphabets, regular languages are exactly the right-linear languages
with a finite nonterminal type. -/
theorem Language.isRegular_iff_exists_rightLinearGrammar
    {T : Type} [Fintype T] {L : Language T} :
    L.IsRegular ↔
      ∃ g : RightLinearGrammar T, Nonempty (Fintype g.cfg.NT) ∧ g.language = L := by
  constructor
  · rintro ⟨σ, inst, M, hM⟩
    classical
    letI : Fintype σ := inst
    let g := Mathling.Automata.DFA.toRightLinearGrammar M
    refine ⟨g, ?_, ?_⟩
    · change Nonempty (Fintype σ)
      exact ⟨inst⟩
    · rw [Mathling.Automata.DFA.toRightLinearGrammar_language]
      exact hM
  · rintro ⟨g, ⟨inst⟩, hL⟩
    letI : Fintype g.cfg.NT := inst
    rw [← hL]
    exact g.language_isRegular

end Mathling.Grammar
