    module

    public import Mathling.Grammar.Core
    public import Mathling.Automata.Core
    public import Mathlib.Data.Fintype.Option
    public import Mathling.Meta.Important

    public import LiterateLean
    open scoped LiterateLean

    @[expose] public section

# Mathling / Grammar / Regular / RightLinear モジュール

右線形文法と有限オートマトンの双方向変換を構成する。帰納的生成関係と NFA の path を対応付ける順方向、および DFA 遷移を生成規則へ符号化する逆方向を通じて、有限アルファベット上の正則性を特徴付ける。

```lean
public section

/-!
# Right-linear grammars

Right-linear grammars, their NFA construction, and the DFA correspondence.
-/

namespace Mathling.Grammar
open Mathling.Automata


namespace RightLinearGrammar

variable {T : Type*}
```

## 言語と忘却写像

`RightLinearGrammar` は文脈自由文法 `cfg` を土台とし、その生成規則が一つの終端記号と高々一つの非終端記号からなる正規形（`rightLinear` フィールド）を満たすことを要求する構造である。`language` は単に `cfg.language` を右線形文法の言語として公開する薄い定義であり、`toLinear` はその正規形が線形文法の条件（非終端記号の出現回数が高々 1 個）を包含することを示し、右線形文法を線形文法へと忘却的に埋め込む。この埋め込みは `ContextFreeRule.IsLinear` の定義を `rightLinear` の三分岐（ε・終端・終端+非終端）に対して機械的に確認するだけであり、以降の NFA 構成や `GeneratesFrom` の議論には使われない。

```lean

/-- The language generated by a right-linear grammar. -/
@[expose] def language (g : RightLinearGrammar T) : Language T := g.cfg.language

/-- Forget that a right-linear grammar is right-linear. -/
def toLinear (g : RightLinearGrammar T) : LinearGrammar T where
  cfg := g.cfg
  linear r hr := by
    rcases g.rightLinear r hr with h | ⟨a, h⟩ | ⟨a, B, h⟩ <;>
      simp [ContextFreeRule.IsLinear, ContextFreeRule.nonterminalCount,
        symbolIsNonterminal, h]
```

## NFA への変換

`toNFA` は右線形文法から NFA を構成する中心的な定義である。状態集合を `Option g.cfg.NT` に取り、`some A` は「非終端記号 `A` から続きを生成する途中」を表し、`none` は「文法規則の終端側で非終端記号を伴わずに文字を出力し終えた直後」を表す番兵状態（sink state）である。遷移 `step (some A) a` は、`A → a` という規則があれば `none` へ、`A → a B` という規則があれば `some B` へ遷移することで、右線形規則の右辺に現れる非終端記号を高々 1 個に制限した正規形をそのまま状態遷移として写し取る。受理状態は `none`（終端規則を経由した直後）と、ε規則 `A → ε` を持つ `some A` の両方であり、これは文法の導出が空語で終わる場合と非空語の末尾で終わる場合の双方に対応する。

```lean

/-- Convert a right-linear grammar to an NFA with a final sink state. -/
def toNFA (g : RightLinearGrammar T) : Mathling.Automata.NFA T (Option g.cfg.NT) where
  step q a := {q' |
    ∃ A, q = some A ∧
      ((q' = none ∧
          ({ input := A, output := [Symbol.terminal a] } :
            ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules) ∨
        ∃ B, q' = some B ∧
          ({ input := A, output := [Symbol.terminal a, Symbol.nonterminal B] } :
            ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules)}
  start := {some g.cfg.initial}
  accept := {q |
    q = none ∨ ∃ A, q = some A ∧
      ({ input := A, output := [] } : ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules}
```

## GeneratesFrom: 導出の帰納的意味論

`GeneratesFrom g A w` は非終端記号 `A` から終端列 `w` を生成するという主張を、Mathlib の一般的な `Derives` 関係を経由せずに直接構造的帰納法で捉え直したものである。右線形文法の規則は `rightLinear` により常に `A → ε`・`A → a`・`A → a B` のいずれかの形に限定されるため、`GeneratesFrom` のコンストラクタもちょうどこの三分岐 `epsilon`・`terminal`・`step` に対応させてある。`epsilon` と `terminal` は基底段（それぞれ空列・単一文字を生成して停止）を、`step` は非終端記号 `B` へ再帰する段（先頭文字 `a` を出力してから `tail : GeneratesFrom g B w` に委ねる）を与える。この帰納的定義は `toNFA` の遷移構造と一対一に対応しており、以降の補題群はこの対応を双方向の同値として確立する。

```lean

@[grind cases] inductive GeneratesFrom (g : RightLinearGrammar T) :
    g.cfg.NT → List T → Prop
  | epsilon {A}
      (h : ({ input := A, output := [] } : ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules) :
      GeneratesFrom g A []
  | terminal {A a}
      (h : ({ input := A, output := [Symbol.terminal a] } :
        ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules) :
      GeneratesFrom g A [a]
  | step {A a B w}
      (h : ({ input := A, output := [Symbol.terminal a, Symbol.nonterminal B] } :
        ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules)
      (tail : GeneratesFrom g B w) :
      GeneratesFrom g A (a :: w)
```

## 書き換え形状に関する補題群

`GeneratesFrom` と Mathlib の `ContextFreeGrammar.Derives` を相互に変換するには、単一の非終端記号からの書き換え・導出がどのような形を取り得るかを補題として先に確立しておく必要がある。`rewrites_singleton_nonterminal` は `[nonterminal A]` に対する一手の書き換えが必ずある規則の `input = A` から `output` への置換であることを述べ、`rule_mem_of_output_eq` はある規則の `output` だけを付け替えた規則もまた文法の規則集合に属することを示す（右線形文法の規則は `output` の形だけで一意に決まるため）。`produces_terminal_cons` と `derives_terminal_cons` は先頭に終端記号 `a` を持つ語からの一手の生成・多段の導出が、先頭の `a` をそのまま残して残りの部分だけを書き換えることを述べ、`derives_nil_eq` は空列からはそれ以上導出できないことを述べる。これらは後続の節から再利用される補助的な事実である。

```lean

@[grind] theorem rewrites_singleton_nonterminal
    {r : ContextFreeRule T N} {A : N} {v : List (Symbol T N)}
    (h : r.Rewrites [Symbol.nonterminal A] v) :
    r.input = A ∧ v = r.output := by
  cases h with
  | head s => exact ⟨rfl, by simp⟩
  | cons _ htail => cases htail

@[grind] theorem rule_mem_of_output_eq
    {g : ContextFreeGrammar T} {r : ContextFreeRule T g.NT}
    (hr : r ∈ g.rules) {output : List (Symbol T g.NT)}
    (hout : r.output = output) :
    ({ input := r.input, output } : ContextFreeRule T g.NT) ∈ g.rules := by
  have heq : ({ input := r.input, output } : ContextFreeRule T g.NT) = r := by
    apply ContextFreeRule.ext
    · rfl
    · exact hout.symm
  simpa only [heq] using hr

@[grind] theorem produces_terminal_cons
    {g : ContextFreeGrammar T} {a : T} {u v : List (Symbol T g.NT)}
    (h : g.Produces (Symbol.terminal a :: u) v) :
    ∃ v', v = Symbol.terminal a :: v' ∧ g.Produces u v' := by
  obtain ⟨r, hr, hw⟩ := h
  cases hw with
  | cons _ htail => exact ⟨_, rfl, ⟨r, hr, htail⟩⟩

@[grind] theorem derives_terminal_cons
    {g : ContextFreeGrammar T} {a : T} {u v : List (Symbol T g.NT)}
    (h : g.Derives (Symbol.terminal a :: u) v) :
    ∃ v', v = Symbol.terminal a :: v' ∧ g.Derives u v' := by
  induction h with
  | refl => exact ⟨u, rfl, .refl u⟩
  | tail hreach hprod ih =>
      obtain ⟨mid, rfl, htail⟩ := ih
      obtain ⟨v', rfl, hstep⟩ := produces_terminal_cons hprod
      exact ⟨v', rfl, htail.trans_produces hstep⟩

@[grind] theorem derives_nil_eq
    {g : ContextFreeGrammar T} {v : List (Symbol T g.NT)}
    (h : g.Derives [] v) : v = [] := by
  induction h with
  | refl => rfl
  | tail _ hprod ih =>
      subst ih
      obtain ⟨r, _, hw⟩ := hprod
      cases hw
```

## GeneratesFrom と Derives の同値性

`generatesFrom_derives` は `GeneratesFrom` による導出を Mathlib の `Derives` へ翻訳する健全性の方向であり、各コンストラクタを対応する一手の `Produces` に置き換えて `Derives` の推移律で繋ぐだけの直接帰納法で証明できる。逆方向の `derives_generatesFrom` は完全性の方向であり、`Derives [nonterminal A] (w.map terminal)` から出発して最初の一手を取り出し、前節の形状補題を使って `rightLinear` の三分岐のどれに該当するかで場合分けし、`step` の場合は残りの導出に対して再帰する。この再帰は生成される語 `w` が真に短くなることに基づくため `termination_by w.length` で整礼性を明示している。両補題を合わせることで `GeneratesFrom g A w ↔ g.cfg.Derives [nonterminal A] (w.map terminal)` が（文として分割されてはいるが）実質的に成立する。

```lean

@[grind] theorem generatesFrom_derives (g : RightLinearGrammar T)
    {A : g.cfg.NT} {w : List T} (h : GeneratesFrom g A w) :
    g.cfg.Derives [Symbol.nonterminal A] (w.map Symbol.terminal) := by
  induction h with
  | epsilon hr =>
      exact ContextFreeGrammar.Produces.single
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩
  | terminal hr =>
      exact ContextFreeGrammar.Produces.single
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩
  | step hr _ ih =>
      exact (ContextFreeGrammar.Produces.single
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩).trans
          (ih.append_left [Symbol.terminal _])

@[grind] theorem derives_generatesFrom (g : RightLinearGrammar T)
    {A : g.cfg.NT} {w : List T}
    (h : g.cfg.Derives [Symbol.nonterminal A] (w.map Symbol.terminal)) :
    GeneratesFrom g A w := by
  rcases h.eq_or_head with heq | ⟨v, hprod, hrest⟩
  · cases w <;> simp at heq
  · obtain ⟨r, hr, hw⟩ := hprod
    obtain ⟨rfl, rfl⟩ := rewrites_singleton_nonterminal hw
    rcases g.rightLinear r hr with hout | ⟨a, hout⟩ | ⟨a, B, hout⟩
    · rw [hout] at hrest
      have hε : ({ input := r.input, output := [] } :
          ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules :=
        rule_mem_of_output_eq hr hout
      have hwNil : w.map Symbol.terminal = [] := derives_nil_eq hrest
      have : w = [] := by
        cases w with
        | nil => rfl
        | cons => simp at hwNil
      subst this
      exact .epsilon hε
    · rw [hout] at hrest
      have hterminal : ({ input := r.input, output := [Symbol.terminal a] } :
          ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules :=
        rule_mem_of_output_eq hr hout
      obtain ⟨tail, htail, hder⟩ := derives_terminal_cons hrest
      have hnil := derives_nil_eq hder
      subst hnil
      cases w with
      | nil => simp at htail
      | cons b ws =>
          simp only [List.map_cons, List.cons.injEq, Symbol.terminal.injEq,
            List.map_eq_nil_iff] at htail
          obtain ⟨rfl, rfl⟩ := htail
          exact .terminal hterminal
    · rw [hout] at hrest
      have hstep :
          ({ input := r.input,
             output := [Symbol.terminal a, Symbol.nonterminal B] } :
            ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules :=
        rule_mem_of_output_eq hr hout
      obtain ⟨tail, htail, hder⟩ := derives_terminal_cons hrest
      cases w with
      | nil => simp at htail
      | cons b ws =>
          simp only [List.map_cons, List.cons.injEq, Symbol.terminal.injEq] at htail
          obtain ⟨rfl, rfl⟩ := htail
          exact .step hstep (derives_generatesFrom g hder)
termination_by w.length
```

## GeneratesFrom と NFA の Path の対応

NFA の受理は `Path` 関係（状態列に沿った遷移の列）によって定義されているため、`GeneratesFrom` を文法の言語と結び付ける最後の一歩は、これを `toNFA` 上の `Path` へ翻訳することである。`generatesFrom_path` は `GeneratesFrom` の各段を `toNFA` の対応する遷移に写し、最終的にいずれかの受理状態（`none` または ε規則を持つ `some A`）へ到達する `Path` を構成する（健全性）。逆方向の `path_accept_generatesFrom` は `some A` から出発し受理状態 `q` に至る `Path` を分解し、その分岐が `toNFA` の定義から `epsilon`・`terminal`・`step` のいずれかに強制されることを示す完全性の方向である。`cons` の場合分けで一度 `simp [toNFA] at hedge'` により矛盾を導く枝があるのは、終端規則の遷移先 `none` からはこの NFA の構成上いかなる遷移も出ないため、`none` を経由した後に `Path` がさらに続くことはあり得ないという不変条件を反映している。

```lean

@[grind] theorem generatesFrom_path (g : RightLinearGrammar T)
    {A : g.cfg.NT} {w : List T} (h : GeneratesFrom g A w) :
    ∃ q ∈ g.toNFA.accept, Nonempty (g.toNFA.Path (some A) q w) := by
  induction h with
  | epsilon hr =>
      exact ⟨some _, by
        exact Or.inr ⟨_, rfl, hr⟩, ⟨.nil _⟩⟩
  | terminal hr =>
      exact ⟨none, Or.inl rfl,
        ⟨.cons none (some _) none _ [] ⟨_, rfl, Or.inl ⟨rfl, hr⟩⟩ (.nil none)⟩⟩
  | step hr _ ih =>
      obtain ⟨q, hq, ⟨path⟩⟩ := ih
      exact ⟨q, hq,
        ⟨.cons (some _) (some _) q _ _ ⟨_, rfl, Or.inr ⟨_, rfl, hr⟩⟩ path⟩⟩

theorem path_accept_generatesFrom (g : RightLinearGrammar T)
    {A : g.cfg.NT} {start q : Option g.cfg.NT} {w : List T} :
    Nonempty (g.toNFA.Path start q w) →
    start = some A → q ∈ g.toNFA.accept →
    GeneratesFrom g A w := by
  rintro ⟨p⟩ hstart hq
  induction p generalizing A with
  | nil state =>
      cases hstart
      rcases hq with hnone | ⟨B, hsome, hr⟩
      · contradiction
      · cases hsome
        exact .epsilon hr
  | cons next start final a tail hedge path ih =>
      cases hstart
      rcases hedge with ⟨B, hsome, hfinal | hnext⟩
      · cases hsome
        obtain ⟨rfl, hr⟩ := hfinal
        cases path with
        | nil => exact .terminal hr
        | cons next' _ _ a' tail' hedge' path' =>
            simp [toNFA] at hedge'
      · cases hsome
        obtain ⟨C, rfl, hr⟩ := hnext
        exact .step hr (ih rfl hq)

grind_pattern path_accept_generatesFrom =>
  g.toNFA.Path start q w, GeneratesFrom g A w
```

## NFA 構成の正しさ

以上の `GeneratesFrom ↔ Derives` と `GeneratesFrom ↔ Path` という二つの橋渡しを合成すれば、`toNFA` が受理する語と文法が生成する語が完全に一致することが従う。`toNFA_language` はこれを `NFA.accepts_iff_exists_path` を介して定式化し、初期状態 `some g.cfg.initial` から出発する経路の存在と `g.language` への所属を同値として結び付ける。

```lean

/-- The NFA construction accepts exactly the grammar's language. -/
@[important, grind =, simp] theorem toNFA_language (g : RightLinearGrammar T) :
    g.toNFA.accepts = g.language := by
  ext w
  rw [_root_.NFA.accepts_iff_exists_path]
  constructor
  · rintro ⟨q, hstart, q', haccept, ⟨path⟩⟩
    have hq : q = some g.cfg.initial := hstart
    subst q
    exact generatesFrom_derives g (path_accept_generatesFrom g ⟨path⟩ rfl haccept)
  · intro h
    have hgen : GeneratesFrom g g.cfg.initial w :=
      derives_generatesFrom g h
    obtain ⟨q, hq, ⟨path⟩⟩ := generatesFrom_path g hgen
    exact ⟨some g.cfg.initial, rfl, q, hq, ⟨path⟩⟩
```

## 有限非終端記号による正則性

`toNFA_language` が確立した言語の一致に、非終端記号の型 `g.cfg.NT` の有限性を仮定として加えれば、`Language.isRegular_iff_nfa` を経由してただちに正則性が従う。`language_isRegular` はこれを定式化した定理であり、`RightLinearGrammar` 名前空間で行ってきた「文法 → NFA」方向の議論はここで完結する。

```lean

/-- A right-linear grammar with finitely many nonterminals generates a regular language. -/
@[grind] theorem language_isRegular (g : RightLinearGrammar T) [Fintype g.cfg.NT] :
    g.language.IsRegular := by
  apply Language.isRegular_iff_nfa.mpr
  exact ⟨Option g.cfg.NT, inferInstance, g.toNFA, g.toNFA_language⟩

end RightLinearGrammar

end Mathling.Grammar
```

## 逆方向: DFA から右線形文法へ

ここからは逆方向、すなわち有限 DFA から右線形文法を構成する方向を扱う。`Mathling.Automata.DFA` 名前空間に定義を置くのは、この構成が本質的に DFA 側の概念（状態・遷移関数・受理状態）だけから決まり、特定の右線形文法に依存しないためである。構成の骨格は `toNFA` の鏡像になっている。`toNFA` が非終端記号を NFA の状態へ、生成規則を状態遷移へ写したのに対し、ここでは逆に DFA の状態そのものを非終端記号の型 `σ` として採用し、DFA の遷移関数 `M.step` と受理述語 `M.accept` を右線形規則へと書き戻す。`transitionRule (q, a)` は `q → a (M.step q a)` という step 規則を、`acceptingRule q` は `q → ε` という epsilon 規則を与え、`dfaRules` はこの二種類の規則を `Finset` の合併として集める。

```lean

namespace Mathling.Automata.DFA

open Mathling.Grammar

variable {T : Type*} {σ : Type}

def transitionRule (M : Mathling.Automata.DFA T σ) (qa : σ × T) :
    ContextFreeRule T σ :=
  { input := qa.1
    output := [Symbol.terminal qa.2, Symbol.nonterminal (M.step qa.1 qa.2)] }

def acceptingRule (q : σ) : ContextFreeRule T σ :=
  { input := q, output := [] }

def dfaRules [Fintype T] [Fintype σ]
    [DecidableEq T] [DecidableEq σ] (M : Mathling.Automata.DFA T σ)
    [DecidablePred (· ∈ M.accept)] : Finset (ContextFreeRule T σ) :=
  (Finset.univ.product Finset.univ).image (transitionRule M) ∪
    (Finset.univ.filter fun q => q ∈ M.accept).image acceptingRule
```

## toRightLinearGrammar の定義

`toRightLinearGrammar` は `dfaRules` を規則集合とし、`M.start` を初期記号とする右線形文法を返す。`rightLinear` の証明では `dfaRules` の非交和分解（`Finset.mem_union`）に沿って場合分けし、`transitionRule` から来た規則は必ず `A → a B` の形（`step` 側の三分岐）に、`acceptingRule` から来た規則は必ず `A → ε` の形（`epsilon` 側）になることを確認するだけであり、`toNFA` 側で状態遷移の定義域を規則の右辺の形に合わせたのとちょうど対称的な整合性の確認になっている。

```lean

/-- Convert a finite DFA to a right-linear grammar. -/
def toRightLinearGrammar [Fintype T] [Fintype σ]
    [DecidableEq T] [DecidableEq σ] (M : Mathling.Automata.DFA T σ)
    [DecidablePred (· ∈ M.accept)] : RightLinearGrammar T :=
  { cfg :=
      { NT := σ
        initial := M.start
        rules := dfaRules M }
    rightLinear := by
      classical
      intro r hr
      change r ∈
        (Finset.univ.product Finset.univ).image (transitionRule M) ∪
          (Finset.univ.filter fun q => q ∈ M.accept).image acceptingRule at hr
      rw [Finset.mem_union, Finset.mem_image, Finset.mem_image] at hr
      rcases hr with ⟨qa, _, rfl⟩ | ⟨q, hq, rfl⟩
      · exact Or.inr (Or.inr ⟨qa.2, M.step qa.1 qa.2, rfl⟩)
      · exact Or.inl rfl }
```

## dfaRules の外延的特徴づけ

`mem_dfaRules` は `Finset` として定義された `dfaRules` への所属を、`transitionRule`・`acceptingRule` の像であるという命題的な言い換えに変換する。以降の証明では `dfaRules` の中身を `Finset.mem_union`/`Finset.mem_image` で直接分解するより、この補題を通して規則の由来（遷移由来か受理由来か）で場合分けする方が見通しがよい。

```lean

@[grind] theorem mem_dfaRules [Fintype T] [Fintype σ]
    [DecidableEq T] [DecidableEq σ] (M : Mathling.Automata.DFA T σ)
    [DecidablePred (· ∈ M.accept)] (r : ContextFreeRule T σ) :
    r ∈ dfaRules M ↔
      (∃ qa : σ × T, transitionRule M qa = r) ∨
      ∃ q ∈ M.accept, acceptingRule q = r := by
  classical
  change r ∈
    (Finset.univ.product Finset.univ).image (transitionRule M) ∪
    (Finset.univ.filter fun q => q ∈ M.accept).image acceptingRule ↔ _
  rw [Finset.mem_union, Finset.mem_image, Finset.mem_image]
  constructor
  · rintro (⟨qa, _, hqa⟩ | ⟨q, hq, hqr⟩)
    · exact Or.inl ⟨qa, hqa⟩
    · exact Or.inr ⟨q, (Finset.mem_filter.mp hq).2, hqr⟩
  · rintro (⟨qa, hqa⟩ | ⟨q, hq, hqr⟩)
    · exact Or.inl ⟨qa, by simp, hqa⟩
    · exact Or.inr ⟨q, Finset.mem_filter.mpr ⟨by simp, hq⟩, hqr⟩

structure DfaSimulation (g : RightLinearGrammar T)
    (M : Mathling.Automata.DFA T σ) where
  encode : g.cfg.NT → σ
  acceptsEpsilon : ∀ A, ({ input := A, output := [] } :
    ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules → encode A ∈ M.accept
  rejectsTerminal : ∀ A a, ({ input := A, output := [Symbol.terminal a] } :
    ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules → False
  preservesStep : ∀ A a B,
    ({ input := A, output := [Symbol.terminal a, Symbol.nonterminal B] } :
      ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules →
    encode B = M.step (encode A) a

theorem generatesFrom_dfa_accept
    (g : RightLinearGrammar T) (M : Mathling.Automata.DFA T σ)
    (simulation : DfaSimulation g M)
    {A : g.cfg.NT} {w : List T} (h : RightLinearGrammar.GeneratesFrom g A w) :
    M.evalFrom (simulation.encode A) w ∈ M.accept := by
  induction h with
  | epsilon hr => simpa using simulation.acceptsEpsilon _ hr
  | terminal hr => exact (simulation.rejectsTerminal _ _ hr).elim
  | step hr _ ih =>
      rw [DFA.evalFrom_cons, ← simulation.preservesStep _ _ _ hr]
      exact ih

grind_pattern generatesFrom_dfa_accept =>
  RightLinearGrammar.GeneratesFrom g A w,
  M.evalFrom (simulation.encode A) w ∈ M.accept

@[grind] theorem generatesFrom_toRightLinearGrammar_iff
    [Fintype T] [Fintype σ] [DecidableEq T] [DecidableEq σ]
    (M : Mathling.Automata.DFA T σ) [DecidablePred (· ∈ M.accept)]
    (q : σ) (w : List T) :
    RightLinearGrammar.GeneratesFrom (toRightLinearGrammar M) q w ↔
      M.evalFrom q w ∈ M.accept := by
  classical
  constructor
  · intro h
    exact generatesFrom_dfa_accept (toRightLinearGrammar M) M
      { encode := id
        acceptsEpsilon := by
          intro A hr
          change σ at A
          change acceptingRule A ∈ dfaRules M at hr
          simpa [mem_dfaRules, acceptingRule, transitionRule] using hr
        rejectsTerminal := by
          intro A a hr
          change σ at A
          change ({ input := A, output := [Symbol.terminal a] } :
            ContextFreeRule T σ) ∈ dfaRules M at hr
          simp [mem_dfaRules, acceptingRule, transitionRule] at hr
        preservesStep := by
          intro A a B hr
          change σ at A B
          change ({ input := A, output := [Symbol.terminal a, Symbol.nonterminal B] } :
            ContextFreeRule T σ) ∈ dfaRules M at hr
          have h := hr
          simp [mem_dfaRules, transitionRule, acceptingRule] at h
          exact h.symm }
      h
  · induction w generalizing q with
    | nil =>
        intro hq
        apply RightLinearGrammar.GeneratesFrom.epsilon
        change acceptingRule q ∈ dfaRules M
        rw [mem_dfaRules]
        exact Or.inr ⟨q, hq, rfl⟩
    | cons a tail ih =>
        intro hq
        apply RightLinearGrammar.GeneratesFrom.step (B := M.step q a)
        · change transitionRule M (q, a) ∈ dfaRules M
          simp [mem_dfaRules]
        · exact ih (M.step q a) (by simpa using hq)

/-- The grammar constructed from a finite DFA generates exactly its language. -/
@[important, grind =, simp] theorem toRightLinearGrammar_language [Fintype T] [Fintype σ]
    [DecidableEq T] [DecidableEq σ] (M : Mathling.Automata.DFA T σ)
    [DecidablePred (· ∈ M.accept)] :
    (toRightLinearGrammar M).language = M.accepts := by
  ext w
  change (toRightLinearGrammar M).cfg.Derives
    [Symbol.nonterminal M.start] (w.map Symbol.terminal) ↔
      M.evalFrom M.start w ∈ M.accept
  rw [← generatesFrom_toRightLinearGrammar_iff M M.start w]
  exact ⟨RightLinearGrammar.derives_generatesFrom (toRightLinearGrammar M),
    RightLinearGrammar.generatesFrom_derives (toRightLinearGrammar M)⟩

```

## 正則言語の右線形文法による特徴付け

DFA から構成した規則の性質をまとめ、有限アルファベット上で「正則であること」と「有限非終端記号を持つ右線形文法が存在すること」の同値を閉じる。ここがオートマトン側と文法側を結ぶ公開境界である。

```lean
end Mathling.Automata.DFA

namespace Mathling.Grammar

/-- Over finite alphabets, regular languages are exactly the right-linear languages
with a finite nonterminal type. -/
@[important, grind =] theorem Language.isRegular_iff_exists_rightLinearGrammar
    {T : Type} [Fintype T] {L : Language T} :
    L.IsRegular ↔
      ∃ g : RightLinearGrammar T, Nonempty (Fintype g.cfg.NT) ∧ g.language = L := by
  constructor
  · rintro ⟨σ, inst, M, hM⟩
    classical
    letI : Fintype σ := inst
    let g := Mathling.Automata.DFA.toRightLinearGrammar M
    refine ⟨g, ?_, ?_⟩
    · change Nonempty (Fintype σ)
      exact ⟨inst⟩
    · rw [Mathling.Automata.DFA.toRightLinearGrammar_language]
      exact hM
  · rintro ⟨g, ⟨inst⟩, hL⟩
    letI : Fintype g.cfg.NT := inst
    rw [← hL]
    exact g.language_isRegular

end Mathling.Grammar

```

<!--
vim: set filetype=markdown :
Local Variables:
mode: markdown
End:
-->
