import Mathlib.Computability.ContextFreeGrammar
import Mathling.Automata.Basic

/-!
# Grammars

Linear and regular grammar classes and their automata constructions.
-/

namespace Mathling.Grammar

open Mathling.Automata

namespace ContextFreeRule

variable {T N : Type*}

/-- The number of nonterminal symbols on the right-hand side of a rule. -/
noncomputable def nonterminalCount (r : ContextFreeRule T N) : Nat := by
  classical
  exact r.output.countP (fun s => ∃ A, s = Symbol.nonterminal A)

/-- A rule is linear when its output contains at most one nonterminal. -/
def IsLinear (r : ContextFreeRule T N) : Prop :=
  Mathling.Grammar.ContextFreeRule.nonterminalCount r ≤ 1

/-- The one-symbol right-linear normal form. -/
def IsRightLinear (r : ContextFreeRule T N) : Prop :=
  r.output = [] ∨
  (∃ a, r.output = [Symbol.terminal a]) ∨
  (∃ a B, r.output = [Symbol.terminal a, Symbol.nonterminal B])

/-- The one-symbol left-linear normal form. -/
def IsLeftLinear (r : ContextFreeRule T N) : Prop :=
  r.output = [] ∨
  (∃ a, r.output = [Symbol.terminal a]) ∨
  (∃ A a, r.output = [Symbol.nonterminal A, Symbol.terminal a])

end ContextFreeRule

/-- A context-free grammar all of whose rules are linear. -/
structure LinearGrammar (T : Type*) where
  cfg : ContextFreeGrammar T
  linear : ∀ r ∈ cfg.rules, Mathling.Grammar.ContextFreeRule.IsLinear r

/-- A context-free grammar in one-symbol right-linear normal form. -/
structure RightLinearGrammar (T : Type*) where
  cfg : ContextFreeGrammar T
  rightLinear : ∀ r ∈ cfg.rules, Mathling.Grammar.ContextFreeRule.IsRightLinear r

/-- A context-free grammar in one-symbol left-linear normal form. -/
structure LeftLinearGrammar (T : Type*) where
  cfg : ContextFreeGrammar T
  leftLinear : ∀ r ∈ cfg.rules, Mathling.Grammar.ContextFreeRule.IsLeftLinear r

namespace LinearGrammar

variable {T : Type*}

/-- The language generated by a linear grammar. -/
def language (g : LinearGrammar T) : Language T := g.cfg.language

end LinearGrammar

namespace RightLinearGrammar

variable {T : Type*}

/-- The language generated by a right-linear grammar. -/
def language (g : RightLinearGrammar T) : Language T := g.cfg.language

/-- Forget that a right-linear grammar is right-linear. -/
noncomputable def toLinear (g : RightLinearGrammar T) : LinearGrammar T where
  cfg := g.cfg
  linear r hr := by
    rcases g.rightLinear r hr with h | ⟨a, h⟩ | ⟨a, B, h⟩
    · simp [ContextFreeRule.IsLinear, ContextFreeRule.nonterminalCount, h]
    · simp [ContextFreeRule.IsLinear, ContextFreeRule.nonterminalCount, h]
    · simp [ContextFreeRule.IsLinear, ContextFreeRule.nonterminalCount, h]

/-- Convert a right-linear grammar to an NFA with a final sink state. -/
def toNFA (g : RightLinearGrammar T) : Mathling.Automata.NFA T (Option g.cfg.NT) where
  step q a := {q' |
    ∃ A, q = some A ∧
      ((q' = none ∧
          ({ input := A, output := [Symbol.terminal a] } :
            ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules) ∨
        ∃ B, q' = some B ∧
          ({ input := A, output := [Symbol.terminal a, Symbol.nonterminal B] } :
            ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules)}
  start := {some g.cfg.initial}
  accept := {q |
    q = none ∨ ∃ A, q = some A ∧
      ({ input := A, output := [] } : ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules}

private inductive GeneratesFrom (g : RightLinearGrammar T) :
    g.cfg.NT → List T → Prop
  | epsilon {A}
      (h : ({ input := A, output := [] } : ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules) :
      GeneratesFrom g A []
  | terminal {A a}
      (h : ({ input := A, output := [Symbol.terminal a] } :
        ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules) :
      GeneratesFrom g A [a]
  | step {A a B w}
      (h : ({ input := A, output := [Symbol.terminal a, Symbol.nonterminal B] } :
        ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules)
      (tail : GeneratesFrom g B w) :
      GeneratesFrom g A (a :: w)

private theorem rewrites_singleton_nonterminal
    {r : ContextFreeRule T N} {A : N} {v : List (Symbol T N)}
    (h : r.Rewrites [Symbol.nonterminal A] v) :
    r.input = A ∧ v = r.output := by
  cases h with
  | head s => exact ⟨rfl, by simp⟩
  | cons _ htail => cases htail

private theorem produces_terminal_cons
    {g : ContextFreeGrammar T} {a : T} {u v : List (Symbol T g.NT)}
    (h : g.Produces (Symbol.terminal a :: u) v) :
    ∃ v', v = Symbol.terminal a :: v' ∧ g.Produces u v' := by
  obtain ⟨r, hr, hw⟩ := h
  cases hw with
  | cons _ htail => exact ⟨_, rfl, ⟨r, hr, htail⟩⟩

private theorem derives_terminal_cons
    {g : ContextFreeGrammar T} {a : T} {u v : List (Symbol T g.NT)}
    (h : g.Derives (Symbol.terminal a :: u) v) :
    ∃ v', v = Symbol.terminal a :: v' ∧ g.Derives u v' := by
  induction h with
  | refl => exact ⟨u, rfl, .refl u⟩
  | tail hreach hprod ih =>
      obtain ⟨mid, rfl, htail⟩ := ih
      obtain ⟨v', rfl, hstep⟩ := produces_terminal_cons hprod
      exact ⟨v', rfl, htail.trans_produces hstep⟩

private theorem derives_nil_eq
    {g : ContextFreeGrammar T} {v : List (Symbol T g.NT)}
    (h : g.Derives [] v) : v = [] := by
  induction h with
  | refl => rfl
  | tail _ hprod ih =>
      subst ih
      obtain ⟨r, _, hw⟩ := hprod
      cases hw

private theorem generatesFrom_derives (g : RightLinearGrammar T)
    {A : g.cfg.NT} {w : List T} (h : GeneratesFrom g A w) :
    g.cfg.Derives [Symbol.nonterminal A] (w.map Symbol.terminal) := by
  induction h with
  | epsilon hr =>
      exact ContextFreeGrammar.Produces.single
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩
  | terminal hr =>
      exact ContextFreeGrammar.Produces.single
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩
  | step hr _ ih =>
      exact (ContextFreeGrammar.Produces.single
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩).trans
          (ih.append_left [Symbol.terminal _])

private theorem derives_generatesFrom (g : RightLinearGrammar T)
    {A : g.cfg.NT} {w : List T}
    (h : g.cfg.Derives [Symbol.nonterminal A] (w.map Symbol.terminal)) :
    GeneratesFrom g A w := by
  rcases h.eq_or_head with heq | ⟨v, hprod, hrest⟩
  · cases w <;> simp at heq
  · obtain ⟨r, hr, hw⟩ := hprod
    obtain ⟨rfl, rfl⟩ := rewrites_singleton_nonterminal hw
    rcases g.rightLinear r hr with hout | ⟨a, hout⟩ | ⟨a, B, hout⟩
    · rw [hout] at hrest
      have hε : ({ input := r.input, output := [] } :
          ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules := by
        have hrule : ({ input := r.input, output := [] } :
            ContextFreeRule T g.cfg.NT) = r := by
          apply ContextFreeRule.ext
          · rfl
          · exact hout.symm
        rwa [hrule]
      have hwNil : w.map Symbol.terminal = [] := derives_nil_eq hrest
      have : w = [] := by
        cases w with
        | nil => rfl
        | cons => simp at hwNil
      subst this
      exact .epsilon hε
    · rw [hout] at hrest
      have hterminal : ({ input := r.input, output := [Symbol.terminal a] } :
          ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules := by
        have hrule : ({ input := r.input, output := [Symbol.terminal a] } :
            ContextFreeRule T g.cfg.NT) = r := by
          apply ContextFreeRule.ext
          · rfl
          · exact hout.symm
        rwa [hrule]
      obtain ⟨tail, htail, hder⟩ := derives_terminal_cons hrest
      have hnil := derives_nil_eq hder
      subst hnil
      cases w with
      | nil => simp at htail
      | cons b ws =>
          simp at htail
          obtain ⟨rfl, rfl⟩ := htail
          exact .terminal hterminal
    · rw [hout] at hrest
      have hstep :
          ({ input := r.input,
             output := [Symbol.terminal a, Symbol.nonterminal B] } :
            ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules := by
        have hrule :
            ({ input := r.input,
               output := [Symbol.terminal a, Symbol.nonterminal B] } :
              ContextFreeRule T g.cfg.NT) = r := by
          apply ContextFreeRule.ext
          · rfl
          · exact hout.symm
        rwa [hrule]
      obtain ⟨tail, htail, hder⟩ := derives_terminal_cons hrest
      cases w with
      | nil => simp at htail
      | cons b ws =>
          simp at htail
          obtain ⟨rfl, rfl⟩ := htail
          exact .step hstep (derives_generatesFrom g hder)
termination_by w.length

private theorem generatesFrom_path (g : RightLinearGrammar T)
    {A : g.cfg.NT} {w : List T} (h : GeneratesFrom g A w) :
    ∃ q ∈ g.toNFA.accept, Nonempty (g.toNFA.Path (some A) q w) := by
  induction h with
  | epsilon hr =>
      exact ⟨some _, by
        exact Or.inr ⟨_, rfl, hr⟩, ⟨.nil _⟩⟩
  | terminal hr =>
      exact ⟨none, Or.inl rfl,
        ⟨.cons none (some _) none _ [] ⟨_, rfl, Or.inl ⟨rfl, hr⟩⟩ (.nil none)⟩⟩
  | step hr _ ih =>
      obtain ⟨q, hq, ⟨path⟩⟩ := ih
      exact ⟨q, hq,
        ⟨.cons (some _) (some _) q _ _ ⟨_, rfl, Or.inr ⟨_, rfl, hr⟩⟩ path⟩⟩

private theorem path_accept_generatesFrom (g : RightLinearGrammar T)
    {A : g.cfg.NT} {start q : Option g.cfg.NT} {w : List T}
    (p : g.toNFA.Path start q w) (hstart : start = some A)
    (hq : q ∈ g.toNFA.accept) :
    GeneratesFrom g A w := by
  induction p generalizing A with
  | nil state =>
      cases hstart
      rcases hq with hnone | ⟨B, hsome, hr⟩
      · contradiction
      · cases hsome
        exact .epsilon hr
  | cons next start final a tail hedge path ih =>
      cases hstart
      rcases hedge with ⟨B, hsome, hfinal | hnext⟩
      · cases hsome
        obtain ⟨rfl, hr⟩ := hfinal
        cases path with
        | nil => exact .terminal hr
        | cons next' _ _ a' tail' hedge' path' =>
            simp [toNFA] at hedge'
      · cases hsome
        obtain ⟨C, rfl, hr⟩ := hnext
        exact .step hr (ih rfl hq)

/-- The NFA construction accepts exactly the grammar's language. -/
@[simp] theorem toNFA_language (g : RightLinearGrammar T) :
    g.toNFA.accepts = g.language := by
  ext w
  rw [_root_.NFA.accepts_iff_exists_path]
  constructor
  · rintro ⟨q, hstart, q', haccept, ⟨path⟩⟩
    have hq : q = some g.cfg.initial := hstart
    subst q
    exact generatesFrom_derives g (path_accept_generatesFrom g path rfl haccept)
  · intro h
    have hgen : GeneratesFrom g g.cfg.initial w :=
      derives_generatesFrom g h
    obtain ⟨q, hq, ⟨path⟩⟩ := generatesFrom_path g hgen
    exact ⟨some g.cfg.initial, rfl, q, hq, ⟨path⟩⟩

/-- A right-linear grammar with finitely many nonterminals generates a regular language. -/
theorem language_isRegular (g : RightLinearGrammar T) [Fintype g.cfg.NT] :
    g.language.IsRegular := by
  apply Language.isRegular_iff_nfa.mpr
  exact ⟨Option g.cfg.NT, inferInstance, g.toNFA, g.toNFA_language⟩

end RightLinearGrammar

namespace LeftLinearGrammar

variable {T : Type*}

/-- The language generated by a left-linear grammar. -/
def language (g : LeftLinearGrammar T) : Language T := g.cfg.language

/-- Forget that a left-linear grammar is left-linear. -/
noncomputable def toLinear (g : LeftLinearGrammar T) : LinearGrammar T where
  cfg := g.cfg
  linear r hr := by
    rcases g.leftLinear r hr with h | ⟨a, h⟩ | ⟨A, a, h⟩
    · simp [ContextFreeRule.IsLinear, ContextFreeRule.nonterminalCount, h]
    · simp [ContextFreeRule.IsLinear, ContextFreeRule.nonterminalCount, h]
    · simp [ContextFreeRule.IsLinear, ContextFreeRule.nonterminalCount, h]

end LeftLinearGrammar

end Mathling.Grammar

namespace Mathling.Automata.DFA

open Mathling.Grammar

variable {T : Type*} {σ : Type}

/-- Convert a finite DFA to a right-linear grammar. -/
noncomputable def toRightLinearGrammar [Fintype T] [Fintype σ]
    (M : Mathling.Automata.DFA T σ) : RightLinearGrammar T := by
  classical
  let transitionRules : Finset (ContextFreeRule T σ) :=
    (Finset.univ.product Finset.univ).image fun qa =>
      { input := qa.1,
        output := [Symbol.terminal qa.2, Symbol.nonterminal (M.step qa.1 qa.2)] }
  let acceptingRules : Finset (ContextFreeRule T σ) :=
    (Finset.univ.filter fun q => q ∈ M.accept).image fun q =>
      { input := q, output := [] }
  refine
    { cfg :=
        { NT := σ
          initial := M.start
          rules := transitionRules ∪ acceptingRules }
      rightLinear := ?_ }
  intro r hr
  simp only [Finset.mem_union, transitionRules, acceptingRules, Finset.mem_image,
    Finset.mem_univ, true_and, Finset.mem_filter] at hr
  rcases hr with ⟨qa, _, rfl⟩ | ⟨q, _, rfl⟩
  · exact Or.inr (Or.inr ⟨qa.2, M.step qa.1 qa.2, rfl⟩)
  · exact Or.inl rfl

private theorem generatesFrom_dfa_accept
    (g : RightLinearGrammar T) (M : Mathling.Automata.DFA T σ)
    (encode : g.cfg.NT → σ)
    (hε : ∀ A, ({ input := A, output := [] } :
      ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules → encode A ∈ M.accept)
    (hterminal : ∀ A a, ({ input := A, output := [Symbol.terminal a] } :
      ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules → False)
    (hstep : ∀ A a B,
      ({ input := A, output := [Symbol.terminal a, Symbol.nonterminal B] } :
        ContextFreeRule T g.cfg.NT) ∈ g.cfg.rules →
      encode B = M.step (encode A) a)
    {A : g.cfg.NT} {w : List T} (h : RightLinearGrammar.GeneratesFrom g A w) :
    M.evalFrom (encode A) w ∈ M.accept := by
  induction h with
  | epsilon hr => simpa using hε _ hr
  | terminal hr => exact (hterminal _ _ hr).elim
  | step hr _ ih =>
      rw [DFA.evalFrom_cons, ← hstep _ _ _ hr]
      exact ih

private theorem generatesFrom_toRightLinearGrammar_iff
    [Fintype T] [Fintype σ] (M : Mathling.Automata.DFA T σ)
    (q : σ) (w : List T) :
    RightLinearGrammar.GeneratesFrom (toRightLinearGrammar M) q w ↔
      M.evalFrom q w ∈ M.accept := by
  classical
  constructor
  · intro h
    apply generatesFrom_dfa_accept (toRightLinearGrammar M) M id
    · intro A hr
      simpa [toRightLinearGrammar] using hr
    · intro A a hr
      simp [toRightLinearGrammar] at hr
    · intro A a B hr
      have h := hr
      simp [toRightLinearGrammar] at h
      exact h.symm
    · exact h
  · induction w generalizing q with
    | nil =>
        intro hq
        apply RightLinearGrammar.GeneratesFrom.epsilon
        simpa [toRightLinearGrammar] using hq
    | cons a tail ih =>
        intro hq
        apply RightLinearGrammar.GeneratesFrom.step (B := M.step q a)
        · simp [toRightLinearGrammar]
        · exact ih (M.step q a) (by simpa using hq)

/-- The grammar constructed from a finite DFA generates exactly its language. -/
@[simp] theorem toRightLinearGrammar_language [Fintype T] [Fintype σ]
    (M : Mathling.Automata.DFA T σ) :
    (toRightLinearGrammar M).language = M.accepts := by
  ext w
  change (toRightLinearGrammar M).cfg.Derives
    [Symbol.nonterminal M.start] (w.map Symbol.terminal) ↔
      M.evalFrom M.start w ∈ M.accept
  rw [← generatesFrom_toRightLinearGrammar_iff M M.start w]
  exact ⟨RightLinearGrammar.derives_generatesFrom (toRightLinearGrammar M),
    RightLinearGrammar.generatesFrom_derives (toRightLinearGrammar M)⟩

end Mathling.Automata.DFA

namespace Mathling.Grammar

/-- Over finite alphabets, regular languages are exactly the right-linear languages
with a finite nonterminal type. -/
theorem Language.isRegular_iff_exists_rightLinearGrammar
    {T : Type} [Fintype T] {L : Language T} :
    L.IsRegular ↔
      ∃ g : RightLinearGrammar T, Nonempty (Fintype g.cfg.NT) ∧ g.language = L := by
  constructor
  · rintro ⟨σ, inst, M, hM⟩
    letI : Fintype σ := inst
    let g := Mathling.Automata.DFA.toRightLinearGrammar M
    refine ⟨g, ?_, ?_⟩
    · change Nonempty (Fintype σ)
      exact ⟨inst⟩
    · rw [Mathling.Automata.DFA.toRightLinearGrammar_language]
      exact hM
  · rintro ⟨g, ⟨inst⟩, hL⟩
    letI : Fintype g.cfg.NT := inst
    rw [← hL]
    exact g.language_isRegular

namespace LeftLinearGrammar

variable {T : Type*}

/-- Reverse every production of a left-linear grammar to obtain a right-linear grammar. -/
def reverseRightLinear (g : LeftLinearGrammar T) : RightLinearGrammar T where
  cfg := g.cfg.reverse
  rightLinear r hr := by
    simp [ContextFreeGrammar.reverse] at hr
    obtain ⟨source, hsource, rfl⟩ := hr
    rcases g.leftLinear source hsource with h | ⟨a, h⟩ | ⟨A, a, h⟩
    · exact Or.inl (by simp [ContextFreeRule.reverse, h])
    · exact Or.inr (Or.inl ⟨a, by simp [ContextFreeRule.reverse, h]⟩)
    · exact Or.inr (Or.inr ⟨a, A, by simp [ContextFreeRule.reverse, h]⟩)

/-- Reversing productions reverses the generated language. -/
@[simp] theorem reverseRightLinear_language (g : LeftLinearGrammar T) :
    g.reverseRightLinear.language = g.language.reverse := by
  simp [reverseRightLinear, RightLinearGrammar.language, LeftLinearGrammar.language]

/-- A left-linear grammar with finitely many nonterminals generates a regular language. -/
theorem language_isRegular (g : LeftLinearGrammar T) [Fintype g.cfg.NT] :
    g.language.IsRegular := by
  letI : Fintype g.reverseRightLinear.cfg.NT := by
    change Fintype g.cfg.NT
    infer_instance
  apply Language.isRegular_reverse_iff.mp
  rw [← g.reverseRightLinear_language]
  exact g.reverseRightLinear.language_isRegular

end LeftLinearGrammar




namespace LinearGrammar

variable {T : Type*}

private abbrev terminalSymbols {N : Type} (w : List T) : List (Symbol T N) :=
  w.map Symbol.terminal

private def isNonterminal {N : Type} : Symbol T N → Bool
  | .terminal _ => false
  | .nonterminal _ => true

private theorem count_nonterminals_eq {N : Type} (r : ContextFreeRule T N) :
    r.output.countP (isNonterminal (T := T)) =
      Mathling.Grammar.ContextFreeRule.nonterminalCount r := by
  classical
  rcases r with ⟨input, output⟩
  induction output with
  | nil => simp [Mathling.Grammar.ContextFreeRule.nonterminalCount]
  | cons symbol rest ih =>
      cases symbol <;>
        simp [isNonterminal, Mathling.Grammar.ContextFreeRule.nonterminalCount, ih]

private theorem terminals_of_count_eq_zero {N : Type}
    (s : List (Symbol T N))
    (h : s.countP (isNonterminal (T := T)) = 0) :
    ∃ w : List T, s = terminalSymbols w := by
  induction s with
  | nil => exact ⟨[], rfl⟩
  | cons symbol s ih =>
      cases symbol with
      | terminal a =>
          have hs : s.countP (isNonterminal (T := T)) = 0 := by
            simpa only [List.countP_cons, isNonterminal, Bool.false_eq_true, if_false,
              zero_add] using h
          obtain ⟨w, rfl⟩ := ih hs
          exact ⟨a :: w, rfl⟩
      | nonterminal A =>
          simp only [List.countP_cons, isNonterminal, if_true] at h
          omega

private theorem split_linear_output {N : Type}
    (s : List (Symbol T N))
    (h : s.countP (isNonterminal (T := T)) ≤ 1) :
    (∃ word : List T, s = terminalSymbols word) ∨
      ∃ pre : List T, ∃ B : N, ∃ suffix : List T,
        s = terminalSymbols pre ++ [Symbol.nonterminal B] ++ terminalSymbols suffix := by
  induction s with
  | nil => exact Or.inl ⟨[], rfl⟩
  | cons symbol s ih =>
      cases symbol with
      | terminal a =>
          have hs : s.countP (isNonterminal (T := T)) ≤ 1 := by
            simpa only [List.countP_cons, isNonterminal, Bool.false_eq_true, if_false,
              zero_add] using h
          rcases ih hs with ⟨word, rfl⟩ | ⟨pre, B, suffix, rfl⟩
          · exact Or.inl ⟨a :: word, rfl⟩
          · exact Or.inr ⟨a :: pre, B, suffix, by simp [terminalSymbols]⟩
      | nonterminal A =>
          have hc : s.countP (isNonterminal (T := T)) + 1 ≤ 1 := by
            simpa only [List.countP_cons, isNonterminal, if_true] using h
          have hz : s.countP (isNonterminal (T := T)) = 0 := by omega
          obtain ⟨suffix, rfl⟩ := terminals_of_count_eq_zero s hz
          exact Or.inr ⟨[], A, suffix, by simp [terminalSymbols]⟩

/-- The production-tree semantics of a linear grammar. -/
inductive LinearGenerates (g : LinearGrammar T) : g.cfg.NT → List T → Prop
  | leaf {r : ContextFreeRule T g.cfg.NT} {word : List T}
      (hr : r ∈ g.cfg.rules) (hout : r.output = terminalSymbols word) :
      LinearGenerates g r.input word
  | branch {r : ContextFreeRule T g.cfg.NT} {pre suffix middle : List T}
      {B : g.cfg.NT}
      (hr : r ∈ g.cfg.rules)
      (hout : r.output =
        terminalSymbols pre ++ [Symbol.nonterminal B] ++ terminalSymbols suffix)
      (child : LinearGenerates g B middle) :
      LinearGenerates g r.input (pre ++ middle ++ suffix)

private theorem generates_derives (g : LinearGrammar T)
    {A : g.cfg.NT} {w : List T} (h : LinearGenerates g A w) :
    g.cfg.Derives [Symbol.nonterminal A] (terminalSymbols w) := by
  induction h with
  | leaf hr hout =>
      have hp : g.cfg.Produces [Symbol.nonterminal _] _ :=
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩
      simpa [hout] using hp.single
  | @branch r pre suffix middle B hr hout child ih =>
      have hp : g.cfg.Produces [Symbol.nonterminal _] _ :=
        ⟨_, hr, ContextFreeRule.Rewrites.input_output⟩
      apply hp.single.trans
      have hctx := (ih.append_left (terminalSymbols pre)).append_right
        (terminalSymbols suffix)
      simpa [hout, terminalSymbols, List.map_append, List.append_assoc] using hctx

private theorem no_rewrites_terminals (r : ContextFreeRule T N)
    {w : List T} {v : List (Symbol T N)}
    (h : r.Rewrites (terminalSymbols w) v) : False := by
  induction w generalizing v with
  | nil => cases h
  | cons a w ih =>
      cases h with
      | cons _ htail => exact ih htail

private theorem rewrites_terminal_context (r : ContextFreeRule T N)
    (left right : List T) (A : N) {v : List (Symbol T N)}
    (h : r.Rewrites
      (terminalSymbols left ++ [Symbol.nonterminal A] ++ terminalSymbols right) v) :
    r.input = A ∧
      v = terminalSymbols left ++ r.output ++ terminalSymbols right := by
  induction left generalizing v with
  | nil =>
      simp only [terminalSymbols, List.map_nil, List.nil_append] at h ⊢
      cases h with
      | head s => exact ⟨rfl, rfl⟩
      | cons _ htail => exact (no_rewrites_terminals r htail).elim
  | cons a left ih =>
      simp only [terminalSymbols, List.map_cons, List.cons_append] at h ⊢
      cases h with
      | cons _ htail =>
          obtain ⟨hin, hout⟩ := ih htail
          exact ⟨hin, congrArg (Symbol.terminal a :: ·) hout⟩

private theorem terminalSymbols_injective {u v : List T}
    (h : (terminalSymbols (N := N) u) = terminalSymbols v) : u = v := by
  induction u generalizing v with
  | nil => simpa [terminalSymbols] using h
  | cons a u ih =>
      cases v with
      | nil => simp [terminalSymbols] at h
      | cons b v =>
          change Symbol.terminal a :: terminalSymbols u =
            Symbol.terminal b :: terminalSymbols v at h
          obtain ⟨hsym, htail⟩ := List.cons.inj h
          cases hsym
          exact congrArg (a :: ·) (ih htail)

private theorem derives_terminals_eq (g : LinearGrammar T) {u v : List T}
    (h : g.cfg.Derives (terminalSymbols u) (terminalSymbols v)) : u = v := by
  rcases h.eq_or_head with heq | ⟨_, ⟨r, _, hr⟩, _⟩
  · exact terminalSymbols_injective heq
  · exact (no_rewrites_terminals r hr).elim

private theorem derives_linear_context (g : LinearGrammar T)
    {form : List (Symbol T g.cfg.NT)} {target : List T}
    (h : g.cfg.Derives form (terminalSymbols target)) :
    ∀ (left right : List T) (A : g.cfg.NT),
      form = terminalSymbols left ++ [Symbol.nonterminal A] ++ terminalSymbols right →
      ∃ middle : List T,
        target = left ++ middle ++ right ∧ LinearGenerates g A middle := by
  induction h using Relation.ReflTransGen.head_induction_on with
  | refl =>
      intro left right A hform
      have hmem : Symbol.nonterminal A ∈ terminalSymbols target := by
        rw [hform]
        simp
      simp [terminalSymbols] at hmem
  | head hprod hrest ih =>
      intro left right A hform
      rcases hprod with ⟨r, hr, hw⟩
      rw [hform] at hw
      obtain ⟨hin, hc⟩ := rewrites_terminal_context r left right A hw
      cases hin
      have hcount : r.output.countP (isNonterminal (T := T)) ≤ 1 := by
        rw [count_nonterminals_eq]
        exact g.linear r hr
      rcases split_linear_output r.output hcount with
        ⟨word, hout⟩ | ⟨pre, B, suffix, hout⟩
      · have hrest' :
            g.cfg.Derives
              (terminalSymbols left ++ r.output ++ terminalSymbols right)
              (terminalSymbols target) := by
          rw [← hc]
          exact hrest
        have hterminal :
            g.cfg.Derives (terminalSymbols (left ++ word ++ right))
              (terminalSymbols target) := by
          rw [hout] at hrest'
          simpa [terminalSymbols, List.map_append, List.append_assoc] using hrest'
        refine ⟨word, (derives_terminals_eq g hterminal).symm, ?_⟩
        exact LinearGenerates.leaf hr hout
      · obtain ⟨middle, heq, hmiddle⟩ :=
          ih (left ++ pre) (suffix ++ right) B (by
            rw [hc, hout]
            simp [terminalSymbols, List.map_append, List.append_assoc])
        refine ⟨pre ++ middle ++ suffix, ?_, ?_⟩
        · simpa [List.append_assoc] using heq
        · exact LinearGenerates.branch hr hout hmiddle

/-- Production trees and context-free derivations agree for linear grammars. -/
theorem linearGenerates_iff (g : LinearGrammar T) (w : List T) :
    LinearGenerates g g.cfg.initial w ↔ w ∈ g.language := by
  constructor
  · exact generates_derives g
  · intro h
    obtain ⟨middle, heq, hmiddle⟩ :=
      derives_linear_context g h [] [] g.cfg.initial rfl
    simp only [List.nil_append, List.append_nil] at heq
    subst middle
    exact hmiddle

/-- Control states for the production-driven linear-grammar PDA. -/
inductive LinearPDAState (g : LinearGrammar T) where
  | derive (A : g.cfg.NT)
  | prefixLeaf (r : ContextFreeRule T g.cfg.NT) (hr : r ∈ g.cfg.rules)
      (word todo : List T) (hout : r.output = terminalSymbols word)
  | prefixBranch (r : ContextFreeRule T g.cfg.NT) (hr : r ∈ g.cfg.rules)
      (pre todo : List T) (B : g.cfg.NT) (suffix : List T)
      (hout : r.output =
        terminalSymbols pre ++ [Symbol.nonterminal B] ++ terminalSymbols suffix)
  | pushBranch (B : g.cfg.NT) (suffix todo : List T)
  | matchStack
  | finished

/-- Local micro-transitions for the linear-grammar PDA. -/
private inductive LinearRawStep (g : LinearGrammar T) :
    LinearPDAState g → Mathling.Automata.TurnPhase → Option T → List T →
      LinearPDAState g → Mathling.Automata.TurnPhase → List T → Prop
  | chooseLeaf {r word stack}
      (hr : r ∈ g.cfg.rules) (hout : r.output = terminalSymbols word) :
      LinearRawStep g (.derive r.input) .push none stack
        (.prefixLeaf r hr word word hout) .push stack
  | chooseBranch {r pre B suffix stack}
      (hr : r ∈ g.cfg.rules)
      (hout : r.output =
        terminalSymbols pre ++ [Symbol.nonterminal B] ++ terminalSymbols suffix) :
      LinearRawStep g (.derive r.input) .push none stack
        (.prefixBranch r hr pre pre B suffix hout) .push stack
  | consumeLeaf {r hr word a todo hout stack} :
      LinearRawStep g (.prefixLeaf r hr word (a :: todo) hout) .push
        (some a) stack (.prefixLeaf r hr word todo hout) .push stack
  | consumeBranch {r hr pre a todo B suffix hout stack} :
      LinearRawStep g (.prefixBranch r hr pre (a :: todo) B suffix hout) .push
        (some a) stack (.prefixBranch r hr pre todo B suffix hout) .push stack
  | finishLeaf {r hr word hout stack} :
      LinearRawStep g (.prefixLeaf r hr word [] hout) .push none stack
        .matchStack .pop stack
  | beginPush {r hr pre B suffix hout stack} :
      LinearRawStep g (.prefixBranch r hr pre [] B suffix hout) .push none stack
        (.pushBranch B suffix suffix.reverse) .push stack
  | push {B suffix a todo stack} :
      LinearRawStep g (.pushBranch B suffix (a :: todo)) .push none stack
        (.pushBranch B suffix todo) .push (a :: stack)
  | continue {B suffix stack} :
      LinearRawStep g (.pushBranch B suffix []) .push none stack
        (.derive B) .push stack
  | matchStack {a stack} :
      LinearRawStep g .matchStack .pop (some a) (a :: stack)
        .matchStack .pop stack
  | finish :
      LinearRawStep g .matchStack .pop none [] .finished .pop []

/-- Convert a linear grammar to a local, production-driven one-turn NPDA. -/
def toOneTurnNPDA (g : LinearGrammar T) :
    Mathling.Automata.OneTurnNPDA T (LinearPDAState g) T where
  step q phase sym stack :=
    {next | LinearRawStep g q phase sym stack next.1 next.2.1 next.2.2}
  start := {.derive g.cfg.initial}
  accept := {.finished}
  initialStack := []
  pop_stays_pop := by
    intro q p sym stack q' p' stack' h hp
    cases h <;> simp_all
  push_phase_nonshrinking := by
    intro q sym stack q' stack' h
    cases h <;> simp
  pop_phase_nongrowing := by
    intro q p sym stack q' stack' h
    cases h <;> simp

private theorem consumeLeaf_reaches (g : LinearGrammar T)
    {r : ContextFreeRule T g.cfg.NT} {hr : r ∈ g.cfg.rules}
    {word : List T} {hout : r.output = terminalSymbols word}
    (todo rest stack : List T) :
    g.toOneTurnNPDA.toNPDA.Reaches
      (todo ++ rest, (.prefixLeaf r hr word todo hout, .push), stack)
      (rest, (.prefixLeaf r hr word [] hout, .push), stack) := by
  induction todo with
  | nil => exact Relation.ReflTransGen.refl
  | cons a todo ih =>
      have hstep : g.toOneTurnNPDA.toNPDA.Step
          (a :: todo ++ rest, (.prefixLeaf r hr word (a :: todo) hout, .push), stack)
          (todo ++ rest, (.prefixLeaf r hr word todo hout, .push), stack) := by
        apply Mathling.Automata.NPDA.Step.consume
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.consumeLeaf
      exact ih.head hstep

private theorem consumeBranch_reaches (g : LinearGrammar T)
    {r : ContextFreeRule T g.cfg.NT} {hr : r ∈ g.cfg.rules}
    {pre : List T} {B : g.cfg.NT} {suffix : List T}
    {hout : r.output =
      terminalSymbols pre ++ [Symbol.nonterminal B] ++ terminalSymbols suffix}
    (todo rest stack : List T) :
    g.toOneTurnNPDA.toNPDA.Reaches
      (todo ++ rest, (.prefixBranch r hr pre todo B suffix hout, .push), stack)
      (rest, (.prefixBranch r hr pre [] B suffix hout, .push), stack) := by
  induction todo with
  | nil => exact Relation.ReflTransGen.refl
  | cons a todo ih =>
      have hstep : g.toOneTurnNPDA.toNPDA.Step
          (a :: todo ++ rest,
            (.prefixBranch r hr pre (a :: todo) B suffix hout, .push), stack)
          (todo ++ rest, (.prefixBranch r hr pre todo B suffix hout, .push), stack) := by
        apply Mathling.Automata.NPDA.Step.consume
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.consumeBranch
      exact ih.head hstep

private theorem pushBranch_reaches (g : LinearGrammar T) (B : g.cfg.NT)
    (suffix todo input stack : List T) :
    g.toOneTurnNPDA.toNPDA.Reaches
      (input, (.pushBranch B suffix todo, .push), stack)
      (input, (.derive B, .push), todo.reverse ++ stack) := by
  induction todo generalizing stack with
  | nil =>
      apply Relation.ReflTransGen.single
      apply Mathling.Automata.NPDA.Step.epsilon
      change LinearRawStep g _ _ _ _ _ _ _
      exact LinearRawStep.continue
  | cons a todo ih =>
      have hstep : g.toOneTurnNPDA.toNPDA.Step
          (input, (.pushBranch B suffix (a :: todo), .push), stack)
          (input, (.pushBranch B suffix todo, .push), a :: stack) := by
        apply Mathling.Automata.NPDA.Step.epsilon
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.push
      have hrest' : g.toOneTurnNPDA.toNPDA.Reaches
          (input, (.pushBranch B suffix todo, .push), a :: stack)
          (input, (.derive B, .push), (a :: todo).reverse ++ stack) := by
        simpa [List.reverse_cons, List.append_assoc] using ih (a :: stack)
      exact hrest'.head hstep

private theorem matchStack_reaches (g : LinearGrammar T) (stack : List T) :
    g.toOneTurnNPDA.toNPDA.Reaches
      (stack, (.matchStack, .pop), stack)
      ([], (.finished, .pop), []) := by
  induction stack with
  | nil =>
      apply Relation.ReflTransGen.single
      apply Mathling.Automata.NPDA.Step.epsilon
      change LinearRawStep g _ _ _ _ _ _ _
      exact LinearRawStep.finish
  | cons a stack ih =>
      have hstep : g.toOneTurnNPDA.toNPDA.Step
          (a :: stack, (.matchStack, .pop), a :: stack)
          (stack, (.matchStack, .pop), stack) := by
        apply Mathling.Automata.NPDA.Step.consume
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.matchStack
      exact ih.head hstep

private theorem generates_reaches (g : LinearGrammar T)
    {A : g.cfg.NT} {word : List T} (h : LinearGenerates g A word)
    (stack : List T) :
    g.toOneTurnNPDA.toNPDA.Reaches
      (word ++ stack, (.derive A, .push), stack)
      ([], (.finished, .pop), []) := by
  induction h generalizing stack with
  | @leaf r word hr hout =>
      have hchoose : g.toOneTurnNPDA.toNPDA.Step
          (word ++ stack, (.derive r.input, .push), stack)
          (word ++ stack, (.prefixLeaf r hr word word hout, .push), stack) := by
        apply Mathling.Automata.NPDA.Step.epsilon
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.chooseLeaf hr hout
      have hconsume := consumeLeaf_reaches g (r := r) (hr := hr)
        (word := word) (hout := hout) word stack stack
      have hpop : g.toOneTurnNPDA.toNPDA.Step
          (stack, (.prefixLeaf r hr word [] hout, .push), stack)
          (stack, (.matchStack, .pop), stack) := by
        apply Mathling.Automata.NPDA.Step.epsilon
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.finishLeaf
      exact ((Relation.ReflTransGen.single hchoose).trans hconsume).tail hpop
        |>.trans (matchStack_reaches g stack)
  | @branch r pre suffix middle B hr hout child ih =>
      have hchoose : g.toOneTurnNPDA.toNPDA.Step
          ((pre ++ middle ++ suffix) ++ stack, (.derive r.input, .push), stack)
          ((pre ++ middle ++ suffix) ++ stack,
            (.prefixBranch r hr pre pre B suffix hout, .push), stack) := by
        apply Mathling.Automata.NPDA.Step.epsilon
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.chooseBranch hr hout
      have hconsume := consumeBranch_reaches g (r := r) (hr := hr)
        (pre := pre) (B := B) (suffix := suffix) (hout := hout)
        pre (middle ++ suffix ++ stack) stack
      have hbegin : g.toOneTurnNPDA.toNPDA.Step
          (middle ++ suffix ++ stack,
            (.prefixBranch r hr pre [] B suffix hout, .push), stack)
          (middle ++ suffix ++ stack,
            (.pushBranch B suffix suffix.reverse, .push), stack) := by
        apply Mathling.Automata.NPDA.Step.epsilon
        change LinearRawStep g _ _ _ _ _ _ _
        exact LinearRawStep.beginPush
      have hpush := pushBranch_reaches g B suffix suffix.reverse
        (middle ++ suffix ++ stack) stack
      have hpush' : g.toOneTurnNPDA.toNPDA.Reaches
          (middle ++ suffix ++ stack,
            (.pushBranch B suffix suffix.reverse, .push), stack)
          (middle ++ suffix ++ stack, (.derive B, .push), suffix ++ stack) := by
        simpa using hpush
      have hchild := ih (suffix ++ stack)
      exact ((Relation.ReflTransGen.single hchoose).trans
        (by simpa [List.append_assoc] using hconsume)).tail hbegin
        |>.trans hpush' |>.trans (by simpa [List.append_assoc] using hchild)

private def LinearGood (g : LinearGrammar T) :
    Mathling.Automata.NPDA.ID T
      (LinearPDAState g × Mathling.Automata.TurnPhase) T → Prop
  | (input, (.derive A, .push), stack) =>
      ∃ word, input = word ++ stack ∧ LinearGenerates g A word
  | (input, (.prefixLeaf _ _ _ todo _, .push), stack) =>
      input = todo ++ stack
  | (input, (.prefixBranch _ _ _ todo B suffix _, .push), stack) =>
      ∃ middle, LinearGenerates g B middle ∧
        input = todo ++ middle ++ suffix ++ stack
  | (input, (.pushBranch B _ todo, .push), stack) =>
      ∃ middle, LinearGenerates g B middle ∧
        input = middle ++ todo.reverse ++ stack
  | (input, (.matchStack, .pop), stack) => input = stack
  | (input, (.finished, _), _) => input = []
  | _ => False

private theorem raw_step_good (g : LinearGrammar T)
    {q q' : LinearPDAState g} {p p' : Mathling.Automata.TurnPhase}
    {sym : Option T} {stack stack' : List T}
    (h : LinearRawStep g q p sym stack q' p' stack') (input : List T) :
    LinearGood g (input, (q', p'), stack') →
      LinearGood g
        ((match sym with | none => input | some a => a :: input), (q, p), stack) := by
  cases h with
  | @chooseLeaf r word stack hr hout =>
      intro hinput
      exact ⟨word, hinput, LinearGenerates.leaf hr hout⟩
  | @chooseBranch r pre B suffix stack hr hout =>
      rintro ⟨middle, hmiddle, hinput⟩
      refine ⟨pre ++ middle ++ suffix, ?_, LinearGenerates.branch hr hout hmiddle⟩
      simpa [List.append_assoc] using hinput
  | consumeLeaf =>
      simp [LinearGood]
  | consumeBranch =>
      simp [LinearGood, List.append_assoc]
  | finishLeaf =>
      simp [LinearGood]
  | beginPush =>
      simp [LinearGood, List.append_assoc]
  | push =>
      simp [LinearGood, List.reverse_cons, List.append_assoc]
  | «continue» =>
      rintro ⟨middle, hinput, hmiddle⟩
      exact ⟨middle, hmiddle, by simpa using hinput⟩
  | matchStack =>
      simp [LinearGood]
  | finish =>
      simp [LinearGood]

private theorem step_good (g : LinearGrammar T)
    {c c' : Mathling.Automata.NPDA.ID T
      (LinearPDAState g × Mathling.Automata.TurnPhase) T}
    (h : g.toOneTurnNPDA.toNPDA.Step c c') :
    LinearGood g c' → LinearGood g c := by
  cases h with
  | consume hraw =>
      change LinearRawStep g _ _ _ _ _ _ _ at hraw
      exact raw_step_good g hraw _
  | epsilon hraw =>
      change LinearRawStep g _ _ _ _ _ _ _ at hraw
      exact raw_step_good g hraw _

private theorem reaches_good (g : LinearGrammar T)
    {c c' : Mathling.Automata.NPDA.ID T
      (LinearPDAState g × Mathling.Automata.TurnPhase) T}
    (h : g.toOneTurnNPDA.toNPDA.Reaches c c') :
    LinearGood g c' → LinearGood g c := by
  induction h using Relation.ReflTransGen.head_induction_on with
  | refl => exact id
  | head hstep _ ih =>
      intro hgood
      exact step_good g hstep (ih hgood)

/-- The local one-turn PDA accepts exactly the language generated by the linear grammar. -/
@[simp] theorem toOneTurnNPDA_language (g : LinearGrammar T) :
    g.toOneTurnNPDA.language = g.language := by
  ext input
  constructor
  · intro hinput
    change g.toOneTurnNPDA.toNPDA.Accepts input at hinput
    rcases hinput with ⟨⟨start, phase⟩, hstart,
      ⟨final, finalPhase⟩, hfinal, stack, hreach⟩
    change start ∈ g.toOneTurnNPDA.start ∧ phase = .push at hstart
    rcases hstart with ⟨hstart, rfl⟩
    change start ∈ ({.derive g.cfg.initial} : Set (LinearPDAState g)) at hstart
    simp only [Set.mem_singleton_iff] at hstart
    subst start
    change final ∈ g.toOneTurnNPDA.accept at hfinal
    change final ∈ ({.finished} : Set (LinearPDAState g)) at hfinal
    simp only [Set.mem_singleton_iff] at hfinal
    subst final
    have hgood : LinearGood g
        (input, (.derive g.cfg.initial, .push), []) :=
      reaches_good g hreach (by simp [LinearGood])
    rcases hgood with ⟨word, hword, hgenerates⟩
    simp only [List.append_nil] at hword
    subst input
    exact (linearGenerates_iff g word).mp hgenerates
  · intro hinput
    have hgenerates := (linearGenerates_iff g input).mpr hinput
    change g.toOneTurnNPDA.toNPDA.Accepts input
    refine ⟨(.derive g.cfg.initial, .push), ?_,
      (.finished, .pop), ?_, [], ?_⟩
    · exact ⟨by simp [toOneTurnNPDA], rfl⟩
    · simp [Mathling.Automata.OneTurnNPDA.toNPDA, toOneTurnNPDA]
    · simpa using generates_reaches g hgenerates []

end LinearGrammar

end Mathling.Grammar
